export const BLOG_POSTS = {
  'whatsapp-canli-destek-ai-handoff': {
    category: { tr: 'WhatsApp', en: 'WhatsApp' },
    title: {
      tr: 'WhatsApp Desteğinde AI’dan Canlı Temsilciye Geçiş Nasıl Kurgulanır?',
      en: 'How to Design AI-to-Human Handoff in WhatsApp Support',
    },
    excerpt: {
      tr: 'Aynı konuşma içinde AI ile başlayıp gerektiğinde canlı ekibe devreden destek akışının en doğru kurgusunu anlatıyoruz.',
      en: 'We explain the cleanest way to start with AI and hand the same conversation over to a live support team when needed.',
    },
    date: '2026-04-08',
    readTime: { tr: '7 dk', en: '7 min' },
    author: 'Telyx Ekibi',
    color: 'from-[#051752] to-[#00C4E6]',
    keywords: [
      'whatsapp ai handoff',
      'whatsapp canlı destek geçişi',
      'ai canlı temsilci handoff',
      'whatsapp business api destek',
      'çok kanallı destek operasyonu',
    ],
    content: {
      tr: [
        { type: 'paragraph', text: 'WhatsApp desteğinde en büyük hata, yapay zekayı ayrı bir kanal, canlı ekibi ayrı bir kanal gibi düşünmektir. Oysa müşteri için önemli olan kanal değil, konuşmanın kesintisiz devam etmesidir. En iyi deneyim, müşterinin aynı thread içinde önce AI’dan yardım alması, gerektiğinde de aynı yazışma içinden canlı desteğe geçebilmesidir.' },
        { type: 'heading', text: 'Handoff Yeni Sohbet Açmak Değildir' },
        { type: 'paragraph', text: 'Canlı destek isteyen müşteriyi farklı bir numaraya, yeni bir forma veya tekrar açıklama yapacağı ikinci bir ekrana yönlendirmek sürtünme yaratır. Handoff mantığında doğru kurgu, mevcut konuşmanın bağlamını korumak ve canlı temsilcinin kaldığı yerden devam etmesini sağlamaktır. Böylece müşteri tekrar sipariş numarası, sorun özeti veya iletişim bilgisi yazmak zorunda kalmaz.' },
        { type: 'heading', text: 'AI Ne Zaman Devreden Çıkmalı?' },
        { type: 'paragraph', text: 'AI destek süreci çoğu soruyu çözebilir; ancak üç durumda canlı desteğe geçiş kritik hale gelir: kullanıcı açıkça insan isterse, sistem aynı konuda iki kez takılırsa veya işlem yüksek güven gerektiriyorsa. Sipariş uyuşmazlıkları, ödeme konuları ve şikayet yönetimi gibi alanlarda canlı destek fallback’i hem müşteri memnuniyetini artırır hem de yanlış cevap riskini azaltır.' },
        { type: 'heading', text: 'Operasyon Ekibi İçin Doğru Arayüz' },
        { type: 'paragraph', text: 'Teknik handoff kadar önemli olan bir diğer konu da ekip arayüzüdür. Bekleyen konuşmaların ayrı görünmesi, bir temsilcinin konuşmayı sahiplenebilmesi, ekip içi çakışmaların engellenmesi ve gerekirse konuşmanın tekrar AI’a devredilebilmesi gerekir. Bu yüzden operasyon ekranında "bekliyor", "canlıda", "AI yönetiyor" gibi net durumlar kritik rol oynar.' },
        { type: 'heading', text: 'En Sağlıklı Akış' },
        { type: 'paragraph', text: 'Pratikte en iyi akış şöyledir: AI çözebiliyorsa devam eder, takıldığı yerde canlı desteği teklif eder, kullanıcı isterse aynı konuşma canlı ekibe geçer ve ekip işi tamamladıktan sonra gerekirse konuşmayı tekrar AI’a bırakır. Bu model hem operasyon ekibine hız kazandırır hem de müşterinin "yeniden başlıyorum" hissini ortadan kaldırır.' },
      ],
      en: [
        { type: 'paragraph', text: 'The biggest mistake in WhatsApp support is treating AI and live support as two separate channels. For the customer, the important thing is not the channel but the continuity of the conversation. The best experience starts with AI and, when needed, moves to a live agent within the same thread.' },
        { type: 'heading', text: 'Handoff Is Not Starting a New Conversation' },
        { type: 'paragraph', text: 'Sending a customer who asks for live support to a different number, form, or second screen creates friction. In a proper handoff model, the context of the current conversation is preserved and the live agent continues exactly where the AI left off. That means the customer does not need to repeat the order number, issue summary, or contact details.' },
        { type: 'heading', text: 'When Should AI Step Back?' },
        { type: 'paragraph', text: 'AI can handle most support interactions, but there are three moments when live support becomes critical: when the user explicitly asks for a human, when the system gets stuck on the same topic twice, or when the issue requires higher confidence. In topics like order disputes, payments, and complaints, live fallback improves customer satisfaction and reduces the risk of wrong answers.' },
        { type: 'heading', text: 'The Right Interface for the Operations Team' },
        { type: 'paragraph', text: 'The technical handoff is only half of the story. The team also needs the right interface: pending conversations should be visible, one agent should be able to claim the thread, agent collisions should be blocked, and the conversation should be returnable to AI when appropriate. That is why clear statuses such as waiting, live, and AI-managed matter so much.' },
        { type: 'heading', text: 'The Healthiest Flow' },
        { type: 'paragraph', text: 'In practice, the strongest model is simple: AI continues while it can solve the issue, offers live support when it gets stuck, hands the same thread to the live team when requested, and lets the team return the conversation to AI if appropriate. This removes the "I have to start over" feeling for the customer while keeping operations fast and controlled.' },
      ],
    },
  },
  'tahsilat-hatirlatma-otomasyonu': {
    category: { tr: 'Operasyon', en: 'Operations' },
    title: {
      tr: 'Tahsilat Hatırlatmalarında Yapay Zeka ile Daha Nazik ve Sistemli Süreçler',
      en: 'Using AI for More Structured and More Polite Payment Reminder Flows',
    },
    excerpt: {
      tr: 'Tahsilat hatırlatmalarını manuel takipten çıkarıp daha düzenli, ölçülebilir ve müşteri dostu hale getirmenin yollarını inceliyoruz.',
      en: 'We explore how to move payment reminders out of manual follow-up and turn them into a measurable, customer-friendly workflow.',
    },
    date: '2026-04-04',
    readTime: { tr: '6 dk', en: '6 min' },
    author: 'Telyx Ekibi',
    color: 'from-[#000ACF] to-[#006FEB]',
    keywords: [
      'tahsilat hatırlatma otomasyonu',
      'borç hatırlatma whatsapp',
      'müşteri ödeme takibi ai',
      'tahsilat sürecini otomatikleştirme',
      'kobi tahsilat yönetimi',
    ],
    content: {
      tr: [
        { type: 'paragraph', text: 'Tahsilat hatırlatmaları birçok işletmede hâlâ manuel takip, Excel listeleri ve dağınık mesajlaşmalar üzerinden ilerliyor. Bu yapı hem operasyon ekibini yoruyor hem de müşteriye düzensiz ve sert görünen bir iletişim deneyimi bırakabiliyor. Yapay zeka destekli hatırlatma akışları ise süreci daha nazik, daha kontrollü ve çok daha ölçülebilir hale getiriyor.' },
        { type: 'heading', text: 'Manuel Takibin En Büyük Sorunu' },
        { type: 'paragraph', text: 'Manuel tahsilat takibinde en sık görülen problemler; kimi aradığınızı karıştırmak, hangi müşteriye ne zaman dönüş yapıldığını takip edememek ve ekip içinde aynı müşteriye çakışan hatırlatmalar göndermektir. Ayrıca tonlama sorunu da yaşanır; bazı hatırlatmalar gereğinden sert, bazıları ise fazla belirsiz kalabilir. Sonuç olarak hem ekip yorulur hem de müşteri deneyimi zarar görür.' },
        { type: 'heading', text: 'Yapay Zeka Burada Ne Değiştirir?' },
        { type: 'paragraph', text: 'AI destekli sistemler hatırlatmaları önceden tanımlanmış politikalara göre tetikleyebilir, müşterinin önceki yanıtlarını dikkate alabilir ve daha doğal bir dil kullanabilir. Böylece hatırlatma mesajları sadece "borcunuz var" diyen tekrarlar olmaktan çıkar; müşterinin durumuna göre nazik, açıklayıcı ve yönlendirici hale gelir. Aynı zamanda tüm sürecin kaydı tutulduğu için ekip hangi müşterinin ne zaman dönüş yaptığını rahatça görür.' },
        { type: 'heading', text: 'Doğru Kanalı Seçmek' },
        { type: 'paragraph', text: 'Her tahsilat hatırlatması telefonla yapılmak zorunda değildir. Bazı müşteriler için WhatsApp mesajı, bazıları için e-posta, bazıları için ise önce yazılı bildirim sonra telefonla takip modeli daha uygundur. Burada önemli olan tek bir kanal değil, kanal geçişlerini düzenli yönetebilmektir. Aynı operasyon ekranı üzerinden bu süreci izlemek ekip için büyük fark yaratır.' },
        { type: 'heading', text: 'Daha Sistemli, Daha Ölçülebilir' },
        { type: 'paragraph', text: 'Tahsilat hatırlatma sürecinin başarılı olması için sadece mesaj göndermek yetmez; hangi hatırlatmanın işe yaradığını da görmek gerekir. Yapay zeka destekli hatırlatma kurgusunda açılma oranı, yanıt oranı, dönüş süresi ve ödeme sonrası kapanış gibi metrikler kolayca izlenebilir. Bu sayede işletme sezgiyle değil, veriyle hareket eder ve tahsilat operasyonu daha öngörülebilir hale gelir.' },
      ],
      en: [
        { type: 'paragraph', text: 'Payment reminders in many businesses still rely on manual follow-ups, spreadsheet lists, and scattered messaging. This puts pressure on the operations team and can create a disorganized or overly harsh customer experience. AI-powered reminder flows make the process more polite, more controlled, and much easier to measure.' },
        { type: 'heading', text: 'The Biggest Problem with Manual Follow-Up' },
        { type: 'paragraph', text: 'The most common issues in manual collection workflows are losing track of who was contacted, not knowing when the customer was last followed up with, and sending overlapping reminders from different team members. Tone is also inconsistent: some reminders come across as too aggressive while others are too vague. The result is friction for both the team and the customer.' },
        { type: 'heading', text: 'What Does AI Change Here?' },
        { type: 'paragraph', text: 'AI-powered systems can trigger reminders according to defined policies, take earlier customer responses into account, and use more natural language. Instead of repeating the same "you have an unpaid balance" message, reminders become clearer, more polite, and more context-aware. Since the whole process is tracked, the team can instantly see who replied and when.' },
        { type: 'heading', text: 'Choosing the Right Channel' },
        { type: 'paragraph', text: 'Not every payment reminder needs a phone call. For some customers, WhatsApp is more effective; for others, email works better; and for some, a written reminder followed by a call is the healthiest model. The key is not a single channel but managing channel transitions in an orderly way. Doing this from one operations workspace makes a significant difference for the team.' },
        { type: 'heading', text: 'More Structured, More Measurable' },
        { type: 'paragraph', text: 'A strong reminder process is not only about sending messages but also about understanding which reminders actually work. In an AI-driven collection flow, metrics such as open rate, response rate, response time, and post-payment closure become easy to track. This helps businesses move from intuition to data and build a more predictable collection operation.' },
      ],
    },
  },
  'cok-kanalli-destek-operasyonlari': {
    category: { tr: 'Destek Operasyonları', en: 'Support Operations' },
    title: {
      tr: 'WhatsApp, Webchat ve E-postayı Tek Ekrandan Yönetmek Neden Fark Yaratır?',
      en: 'Why Managing WhatsApp, Webchat, and Email from One Screen Changes Operations',
    },
    excerpt: {
      tr: 'Kanallar ayrı ayrı yönetildiğinde ekipler zaman kaybediyor. Tek bir operasyon ekranının neden daha hızlı ve daha kontrollü çalıştığını anlatıyoruz.',
      en: 'Teams lose time when channels are managed separately. We explain why a unified operations workspace is faster and easier to control.',
    },
    date: '2026-03-27',
    readTime: { tr: '5 dk', en: '5 min' },
    author: 'Telyx Ekibi',
    color: 'from-[#006FEB] to-[#00C4E6]',
    keywords: [
      'çok kanallı destek',
      'omnichannel müşteri hizmetleri',
      'tek panel destek',
      'whatsapp e-posta birleşik',
      'destek operasyon ekranı',
    ],
    content: {
      tr: [
        { type: 'paragraph', text: 'Destek ekipleri çoğu zaman WhatsApp\'ı ayrı, webchat\'i ayrı, e-postayı ayrı araçlardan yönetiyor. Bu da sadece ekran sayısını artırmakla kalmıyor; ekip içinde önceliklendirme, sahiplenme ve takip süreçlerini de karmaşıklaştırıyor. Tek ekran yaklaşımı ise operasyonları sadeleştiriyor ve ekibin dikkatini doğru yere topluyor.' },
        { type: 'heading', text: 'Asıl Sorun Kanal Sayısı Değil, Dağınık Operasyon' },
        { type: 'paragraph', text: 'Kanal sayısının artması tek başına problem değildir. Problem, her kanalın kendi ayrı inbox\'ı, kendi ayrı takibi ve kendi ayrı sahiplenme mantığıyla ilerlemesidir. Böyle olduğunda aynı müşteri bir yandan e-posta gönderirken diğer yandan WhatsApp\'tan yazabilir ve ekip bu bağlantıyı kaçırabilir. Sonuç, geç cevaplar ve tekrarlayan iş yüküdür.' },
        { type: 'heading', text: 'Tek Ekran Ne Sağlar?' },
        { type: 'paragraph', text: 'Tek operasyon ekranı, ekibe önce en önemli işi gösterir. Hangi konuşma bekliyor, hangisi canlı destek istiyor, hangisi AI tarafından yönetiliyor, hangisi kapanmış; tüm bunlar tek listede görünür. Bu yaklaşım sadece hız kazandırmaz, aynı zamanda karar yorgunluğunu azaltır. Temsilciler "hangi sekmeye bakmalıyım" diye düşünmez, doğrudan sıradaki işe geçer.' },
        { type: 'heading', text: 'Handoff ve Sahiplenme Daha Temiz Çalışır' },
        { type: 'paragraph', text: 'Çok kanallı destek operasyonlarının kritik noktası sahiplenmedir. Bir temsilcinin konuşmayı devralması, diğer ekip arkadaşlarının bunu anında görmesi ve konuşmanın gereksiz yere iki kişi tarafından yönetilmemesi gerekir. Tek ekran modeli, bu tür çakışmaları azaltır ve canlı handoff akışını çok daha temiz hale getirir.' },
        { type: 'heading', text: 'Yönetim Açısından Da Daha Güçlü' },
        { type: 'paragraph', text: 'Tek bir operasyon ekranı sadece ekip için değil, yöneticiler için de avantaj sağlar. Hangi kanal daha çok yük üretiyor, nerede handoff artıyor, ekip hangi konularda en çok zorlanıyor gibi sorulara cevap bulmak kolaylaşır. Bu sayede kanal bazlı dağınık raporlar yerine tek bakışta okunabilen bir operasyon resmi oluşur.' },
      ],
      en: [
        { type: 'paragraph', text: 'Support teams often manage WhatsApp, webchat, and email from separate tools. This does not only increase the number of screens they watch; it also complicates prioritization, ownership, and follow-up. A single operations workspace simplifies support work and helps the team focus on what matters most.' },
        { type: 'heading', text: 'The Real Problem Is Not Channel Count, but Operational Fragmentation' },
        { type: 'paragraph', text: 'Having multiple channels is not the problem by itself. The problem starts when each channel comes with its own inbox, ownership rules, and follow-up habits. In that setup, the same customer can send an email while also writing on WhatsApp, and the team can easily miss the connection. The result is delayed responses and repeated work.' },
        { type: 'heading', text: 'What Does a Unified Workspace Provide?' },
        { type: 'paragraph', text: 'A unified operations screen shows the team the most important work first. Which conversation is waiting, which one needs live support, which one is AI-managed, and which one is already resolved can all be seen in a single list. This does not only make the team faster; it also reduces decision fatigue. Agents stop wondering which tab to check next.' },
        { type: 'heading', text: 'Handoff and Ownership Work More Cleanly' },
        { type: 'paragraph', text: 'Ownership is the critical point in multi-channel support operations. When one agent claims a conversation, the rest of the team should see that immediately, and the same conversation should not be actively handled by multiple people. A single-screen model reduces these collisions and makes live handoff flows far cleaner.' },
        { type: 'heading', text: 'It Is Stronger for Management Too' },
        { type: 'paragraph', text: 'A unified operations workspace is not only good for agents; it is also better for managers. It becomes easier to answer questions like which channel creates the most load, where handoff requests are increasing, and which topics challenge the team the most. Instead of fragmented channel-based reports, the business gets one clear operational picture.' },
      ],
    },
  },
  'ai-musteri-hizmetleri-gelecegi': {
    category: { tr: 'AI & Teknoloji', en: 'AI & Technology' },
    title: {
      tr: 'AI ile Müşteri Hizmetlerinin Geleceği: 2026 Trendleri',
      en: 'The Future of Customer Service with AI: 2026 Trends',
    },
    excerpt: {
      tr: 'Yapay zeka destekli müşteri hizmetleri hızla dönüşüyor. İşletmelerin bu değişime nasıl uyum sağlayabileceğini keşfedin.',
      en: 'AI-powered customer service is rapidly transforming. Discover how businesses can adapt to this change.',
    },
    date: '2026-03-15',
    readTime: { tr: '5 dk', en: '5 min' },
    author: 'Telyx Ekibi',
    color: 'from-[#000ACF] to-[#00C4E6]',
    keywords: [
      'ai müşteri hizmetleri 2026',
      'yapay zeka müşteri hizmetleri trend',
      'omnichannel ai',
      'proaktif müşteri hizmeti',
      'konuşanabilir ai',
    ],
    content: {
      tr: [
        { type: 'paragraph', text: 'Yapay zeka teknolojileri, müşteri hizmetleri alanında devrim yaratmaya devam ediyor. 2026 yılına geldiğimizde, işletmelerin müşterileriyle iletişim kurma biçimi kökten değişti. Artık müşteriler 7/24 anında yanıt bekliyor, kişiselleştirilmiş deneyimler talep ediyor ve çoklu kanal üzerinden kesintisiz hizmet almak istiyor. Bu beklentileri karşılamak için yapay zeka destekli çözümler vazgeçilmez hale geldi.' },
        { type: 'heading', text: 'Konuşanabilir Yapay Zeka Yeni Standart' },
        { type: 'paragraph', text: 'Eskiden chatbotlar belirli anahtar kelimelere göre önceden programlanmış yanıtlar verirdi. Bugün ise büyük dil modelleri (LLM) sayesinde yapay zeka asistanları doğal dilde anlama, bağlamsal yanıt üretme ve karmaşık sorunları çözme yeteneğine sahip. 2026\'da konuşanabilir AI, müşteri hizmetlerinde altın standart haline geldi. Müşteriler artık bir robotla değil, gerçekten anlayan ve yardımcı olan bir asistanla konuştuğunu hissediyor.' },
        { type: 'heading', text: 'Omnichannel Deneyim: Tek Noktadan Yönetim' },
        { type: 'paragraph', text: 'Müşteriler artık tek bir kanalda kalmak istemiyor. WhatsApp\'tan başlayan bir konuşmayı e-posta ile sürdürmeyi, web sitenizden başlatılan bir talebi telefonla takip etmeyi bekliyorlar. 2026\'nın en belirgin trendi, tüm kanalların tek bir yapay zeka asistanı tarafından yönetilmesi. Bu sayede müşteri hangi kanaldan ulaşırsa ulaşsın, önceki konuşmaları bilgi kaybetmeden sürdürülür ve işletmeniz tutarlı bir deneyim sunar.' },
        { type: 'heading', text: 'Proaktif Müşteri Hizmeti' },
        { type: 'paragraph', text: 'Reaktif yaklaşım, yani müşterinin sorun yaşayıp sizi aramasını beklemek artık geride kaldı. Yapay zeka destekli sistemler, müşteri davranışlarını analiz ederek potansiyel sorunları önceden tespit edebiliyor. Örneğin bir e-ticaret sitesinde kargonun gecikmesi tahmin edildiğinde, müşteri şikayetçiye dönmeden önce bilgilendirme mesajı gönderiliyor. Bu proaktif yaklaşım, müşteri memnuniyetini ortalama yüzde 35 artırıyor.' },
        { type: 'heading', text: 'İşletmeler Nasıl Uyum Sağlayabilir?' },
        { type: 'paragraph', text: 'Bu dönüşüme ayak uydurmak isteyen işletmelerin atması gereken adımlar net: İlk olarak, mevcut müşteri hizmetleri süreçlerinizi analiz edin ve tekrarlayan görevleri belirleyin. İkinci olarak, tüm kanallarınızı tek bir platformda birleştirin. Üçüncü olarak, yapay zeka çözümünüzü kendi iş süreçlerinize ve verilerinize göre eğiterek kişiselleştirilmiş yanıt üretme kapasitesini artırın. Son olarak, insan operatörler ile yapay zeka arasında sorunsuz bir geçiş mekanizması kurun. Telyx gibi entegre AI platformları, tüm bu adımları tek bir çatı altında sunarak işletmelerin dönüşüm sürecini hızlandırıyor.' },
      ],
      en: [
        { type: 'paragraph', text: 'Artificial intelligence technologies continue to revolutionize the customer service industry. As we enter 2026, the way businesses communicate with their customers has fundamentally changed. Customers now expect instant 24/7 responses, demand personalized experiences, and want seamless service across multiple channels. AI-powered solutions have become indispensable to meet these expectations.' },
        { type: 'heading', text: 'Conversational AI Is the New Standard' },
        { type: 'paragraph', text: 'In the past, chatbots gave pre-programmed responses based on specific keywords. Today, thanks to large language models (LLMs), AI assistants have the ability to understand natural language, generate contextual responses, and solve complex problems. In 2026, conversational AI has become the gold standard in customer service. Customers now feel like they are talking to an assistant that truly understands and helps them, not a robot.' },
        { type: 'heading', text: 'Omnichannel Experience: Single Point of Management' },
        { type: 'paragraph', text: 'Customers no longer want to stay on a single channel. They expect to continue a conversation that started on WhatsApp via email, and follow up a request initiated from your website by phone. The most prominent trend of 2026 is having all channels managed by a single AI assistant. This way, regardless of which channel the customer uses, their previous conversations continue without information loss and your business delivers a consistent experience.' },
        { type: 'heading', text: 'Proactive Customer Service' },
        { type: 'paragraph', text: 'The reactive approach of waiting for customers to experience a problem and contact you is now a thing of the past. AI-powered systems can analyze customer behavior and detect potential issues in advance. For example, when a shipping delay is predicted on an e-commerce site, an informational message is sent before the customer becomes a complainer. This proactive approach increases customer satisfaction by an average of 35 percent.' },
        { type: 'heading', text: 'How Can Businesses Adapt?' },
        { type: 'paragraph', text: 'The steps businesses need to take to keep up with this transformation are clear: First, analyze your existing customer service processes and identify repetitive tasks. Second, unify all your channels on a single platform. Third, train your AI solution on your own business processes and data to increase personalized response capacity. Finally, establish a seamless handoff mechanism between human operators and AI. Integrated AI platforms like Telyx accelerate the transformation process by offering all these steps under one roof.' },
      ],
    },
  },
  'whatsapp-business-api-rehberi': {
    category: { tr: 'Rehber', en: 'Guide' },
    title: {
      tr: 'WhatsApp Business API: Eksiksiz Başlangıç Rehberi',
      en: 'WhatsApp Business API: Complete Getting Started Guide',
    },
    excerpt: {
      tr: 'WhatsApp Business API nedir, nasıl entegre edilir ve işletmenize nasıl değer katar? Adım adım rehberimizle öğrenin.',
      en: 'What is WhatsApp Business API, how to integrate it, and how does it add value to your business? Learn with our step-by-step guide.',
    },
    date: '2026-03-01',
    readTime: { tr: '8 dk', en: '8 min' },
    author: 'Telyx Ekibi',
    color: 'from-[#051752] to-[#006FEB]',
    keywords: [
      'whatsapp business api rehberi',
      'whatsapp business api kurulum',
      'whatsapp business api türkiye',
      'whatsapp api entegrasyonu',
      'meta business solution provider',
    ],
    content: {
      tr: [
        { type: 'paragraph', text: 'WhatsApp, dünya genelinde 2 milyardan fazla aktif kullanıcısıyla en popüler mesajlaşma platformu olmaya devam ediyor. Türkiye\'de ise neredeyse her akıllı telefon kullanıcısının günlük hayatında vazgeçilmez bir yere sahip. İşletmeler için WhatsApp Business API, müşterilerle doğal iletişim kurmanın, destek sunmanın ve hatta satış yapmanın en etkili yollarından biri haline geldi.' },
        { type: 'heading', text: 'WhatsApp Business API Nedir?' },
        { type: 'paragraph', text: 'WhatsApp Business API, standart WhatsApp Business uygulamasından farklı olarak işletmelere programatik erişim sağlayan bir arayüzdür. Bu API sayesinde otomatik mesaj gönderebilir, chatbot entegrasyonu yapabilir, CRM sisteminize bağlayabilir ve binlerce müşteriye aynı anda hizmet verebilirsiniz. Küçük işletmeler için tasarlanan WhatsApp Business uygulamasının aksine API, ölçeklenebilir ve kurumsal düzeyde çözümler sunar.' },
        { type: 'heading', text: 'WhatsApp Business API\'nin İşletmenize Kattığı Değer' },
        { type: 'paragraph', text: 'Müşterileriniz zaten WhatsApp kullanıyorsa, onlara en rahat ettikleri platformda ulaşabilmeniz büyük avantaj. API entegrasyonunun sağladığı temel faydalar şunlardır: Birincisi, mesaj açılma oranları e-postaya kıyasla çok daha yüksektir; ortalama yüzde 98 açılma oranı ile neredeyse her mesajınız okunur. İkincisi, 7/24 otomatik yanıt verme yeteneğiyle müşteri bekleme sürelerini sıfıra indirebilirsiniz. Üçüncüsü, sipariş takibi, randevu hatırlatma ve kampanya bildirimleri gibi işlemleri otomatikleştirerek operasyonel yükü azaltırsınız.' },
        { type: 'heading', text: 'Entegrasyon Adımları' },
        { type: 'paragraph', text: 'WhatsApp Business API entegrasyonu için izlemeniz gereken adımlar şunlardır: İlk olarak bir Meta Business hesabı oluşturun ve işletmenizi doğrulayın. Ardından bir Business Solution Provider (BSP) seçin; Telyx gibi platformlar bu süreci sizin için yönetir ve teknik karmaşıklığı ortadan kaldırır. Telefon numaranızı WhatsApp Business API\'ye kaydedin. Mesaj şablonlarınızı oluşturun ve Meta\'nın onayına gönderin. Son olarak webhook entegrasyonunuzu yapın ve gelen mesajları kendi sisteminize yönlendirin. Telyx kullanıyorsanız tüm bu adımlar tek bir panel üzerinden, kod yazmadan tamamlanabilir.' },
        { type: 'heading', text: 'Başarılı Bir WhatsApp Stratejisi İçin İpuçları' },
        { type: 'paragraph', text: 'WhatsApp Business API\'yi etkili kullanmak için bazı temel kurallara dikkat etmeniz önemlidir. Her şeyden önce, müşterilerinize spam göndermeyin; WhatsApp\'ın katı politikaları vardır ve ihlaller numaranızın engellenmesine yol açabilir. Mesaj şablonlarınızı kısa, net ve değer odaklı tutun. Chatbot ile insan operatörler arasında yumuşak bir geçiş mekanizması kurun; yapay zekanın çözemediği durumlarda müşterinin insan bir temsilciye ulaşabilmesini sağlayın. Son olarak, performans metriklerinizi düzenli takip edin: yanıt süresi, çözüm oranı ve müşteri memnuniyeti skorları size yol gösterecektir.' },
      ],
      en: [
        { type: 'paragraph', text: 'WhatsApp continues to be the most popular messaging platform worldwide with over 2 billion active users. In Turkey, it holds an indispensable place in almost every smartphone user\'s daily life. For businesses, WhatsApp Business API has become one of the most effective ways to communicate naturally with customers, provide support, and even make sales.' },
        { type: 'heading', text: 'What Is WhatsApp Business API?' },
        { type: 'paragraph', text: 'Unlike the standard WhatsApp Business app, WhatsApp Business API is an interface that provides businesses with programmatic access. With this API, you can send automated messages, integrate chatbots, connect to your CRM system, and serve thousands of customers simultaneously. Unlike the WhatsApp Business app designed for small businesses, the API offers scalable, enterprise-grade solutions.' },
        { type: 'heading', text: 'The Value WhatsApp Business API Adds to Your Business' },
        { type: 'paragraph', text: 'If your customers already use WhatsApp, being able to reach them on the platform where they are most comfortable is a huge advantage. The key benefits of API integration are: First, message open rates are much higher compared to email; with an average 98 percent open rate, almost every message you send is read. Second, with 24/7 automated response capability, you can reduce customer waiting times to zero. Third, you reduce operational burden by automating processes like order tracking, appointment reminders, and campaign notifications.' },
        { type: 'heading', text: 'Integration Steps' },
        { type: 'paragraph', text: 'The steps you need to follow for WhatsApp Business API integration are: First, create a Meta Business account and verify your business. Then choose a Business Solution Provider (BSP); platforms like Telyx manage this process for you and eliminate technical complexity. Register your phone number with WhatsApp Business API. Create your message templates and submit them for Meta approval. Finally, set up your webhook integration and route incoming messages to your own system. If you are using Telyx, all these steps can be completed through a single panel without writing code.' },
        { type: 'heading', text: 'Tips for a Successful WhatsApp Strategy' },
        { type: 'paragraph', text: 'To use WhatsApp Business API effectively, you need to pay attention to some fundamental rules. Above all, do not spam your customers; WhatsApp has strict policies and violations can lead to your number being blocked. Keep your message templates short, clear, and value-focused. Set up a smooth handoff mechanism between chatbot and human operators; ensure customers can reach a human representative when AI cannot resolve the issue. Finally, regularly track your performance metrics: response time, resolution rate, and customer satisfaction scores will guide you.' },
      ],
    },
  },
  'e-ticaret-chatbot-karsilastirma': {
    category: { tr: 'E-ticaret', en: 'E-commerce' },
    title: {
      tr: 'E-ticaret İçin En İyi Chatbot Çözümleri: 2026 Karşılaştırması',
      en: 'Best Chatbot Solutions for E-commerce: 2026 Comparison',
    },
    excerpt: {
      tr: 'E-ticaret siteniz için doğru chatbot çözümünü seçmek kritik. Piyasadaki seçenekleri ve Telyx\'in farkını karşılaştırıyoruz.',
      en: 'Choosing the right chatbot solution for your e-commerce site is critical. We compare market options and what sets Telyx apart.',
    },
    date: '2026-02-15',
    readTime: { tr: '6 dk', en: '6 min' },
    author: 'Telyx Ekibi',
    color: 'from-orange-500 to-red-500',
    keywords: [
      'e-ticaret chatbot karşılaştırma',
      'en iyi e-ticaret chatbot',
      'shopify chatbot',
      'ikas chatbot',
      'e-ticaret ai müşteri hizmetleri',
    ],
    content: {
      tr: [
        { type: 'paragraph', text: 'E-ticaret sektöründe rekabet her geçen gün artarken, müşteri deneyimini iyileştirmek ve satış dönüşüm oranlarını yükseltmek için chatbot çözümleri kritik bir araca dönüştü. Ancak piyasada onlarca farklı çözüm mevcut ve doğru seçimi yapmak kolay değil. Bu yazıda, 2026 itibarıyla e-ticaret işletmeleri için en iyi chatbot çözümlerini karşılaştırıyor ve işletmeniz için en uygun seçimi yapmanıza yardımcı oluyoruz.' },
        { type: 'heading', text: 'E-ticaret Chatbotlarında Dikkat Edilmesi Gerekenler' },
        { type: 'paragraph', text: 'Bir chatbot çözümü seçerken dikkat etmeniz gereken temel kriterler şunlardır: Doğal dil anlama kapasitesi (NLU), e-ticaret platformunuzla entegrasyon kolaylığı, çoklu kanal desteği (web, WhatsApp, Instagram, e-posta), sipariş takibi ve müşteri verilerine erişim yetkinliği, ölçeklenebilirlik ve maliyet yapısı. Ayrıca chatbotun öğrenim kapasitesi de önemlidir; zamanla müşteri davranışlarından öğrenebilen ve kendini geliştirebilen bir sistem, statik bir kural tabanlı bota göre çok daha fazla değer üretir.' },
        { type: 'heading', text: 'Piyasadaki Genel Eğilimler' },
        { type: 'paragraph', text: '2026 yılında e-ticaret chatbot pazarında belirgin eğilimler gözlemliyoruz. İlk olarak, kural tabanlı chatbotlar hızla yerini LLM destekli konuşanabilir AI sistemlerine bırakıyor. İkinci olarak, chatbotlar artık sadece destek değil, aktif satış aracı olarak da kullanılıyor; ürün önerisi, çoklu satış ve terk edilen sepet kurtarma gibi senaryolarda gerçek gelir yaratıyor. Üçüncü olarak, omnichannel yaklaşım artık bir lüks değil zorunluluk; müşteriler WhatsApp\'tan başladığı konuşmayı web\'de sürdürmeyi, e-postayla takip etmeyi bekliyor.' },
        { type: 'heading', text: 'Telyx Farkı: Yapay Zeka Öncelikli Mimari' },
        { type: 'paragraph', text: 'Telyx, e-ticaret chatbot pazarında farklı bir yaklaşım benimsemektedir. Birçoğu chatbot çözümü hâlâ kural tabanlı mantık üzerine kuruluyken, Telyx sıfırdan yapay zeka öncelikli bir mimariyle inşa edildi. Bu ne anlama geliyor? Telyx\'in AI asistanı, işletmenizin ürün kataloğunu, sipariş geçmişini ve müşteri verilerini anlayarak bağlamsal ve kişiselleştirilmiş yanıtlar üretiyor. Bir müşteri sipariş durumunu sorduğunda, asistan gerçek zamanlı olarak kargo bilgisine erişir ve doğru bilgiyi sunar; tahmin yürütmez.' },
        { type: 'heading', text: 'Doğru Çözümü Seçmek İçin Kontrol Listesi' },
        { type: 'paragraph', text: 'E-ticaret siteniz için chatbot çözümü seçerken şu soruları sorun: Çözüm, kullandığınız e-ticaret platformuyla (Shopify, WooCommerce, Trendyol, Hepsiburada vb.) sorunsuz entegre olabiliyor mu? Türkçe doğal dil anlama kapasitesi yeterli mi? Sipariş takibi ve müşteri doğrulama gibi gerçek iş süreçlerini yönetebiliyor mu? WhatsApp, e-posta ve web chat gibi tüm kanallarınızı tek bir yerden yönetmenize olanak tanıyor mu? Maliyet yapısı işletmenizin ölçeğine uygun mu? Bu sorulara olumlu yanıt veren bir çözüm, e-ticaret operasyonlarınızı bir üst seviyeye taşıyacaktır. Telyx, tüm bu kriterleri karşılayacak şekilde tasarlanmış entegre bir platformdur.' },
      ],
      en: [
        { type: 'paragraph', text: 'As competition in the e-commerce sector grows every day, chatbot solutions have become a critical tool for improving customer experience and increasing sales conversion rates. However, with dozens of different solutions available in the market, making the right choice is not easy. In this article, we compare the best chatbot solutions for e-commerce businesses as of 2026 and help you make the most suitable choice for your business.' },
        { type: 'heading', text: 'What to Look for in E-commerce Chatbots' },
        { type: 'paragraph', text: 'The key criteria to consider when choosing a chatbot solution are: Natural language understanding (NLU) capacity, ease of integration with your e-commerce platform, multi-channel support (web, WhatsApp, Instagram, email), order tracking and customer data access capabilities, scalability, and cost structure. Additionally, the chatbot\'s learning capacity is important; a system that can learn from customer behavior over time and improve itself generates much more value than a static rule-based bot.' },
        { type: 'heading', text: 'General Market Trends' },
        { type: 'paragraph', text: 'In 2026, we observe clear trends in the e-commerce chatbot market. First, rule-based chatbots are rapidly giving way to LLM-powered conversational AI systems. Second, chatbots are now used not just for support but as active sales tools; generating real revenue in scenarios like product recommendations, cross-selling, and abandoned cart recovery. Third, an omnichannel approach is no longer a luxury but a necessity; customers expect to continue a conversation started on WhatsApp on the web and follow up via email.' },
        { type: 'heading', text: 'The Telyx Difference: AI-First Architecture' },
        { type: 'paragraph', text: 'Telyx takes a different approach in the e-commerce chatbot market. While many chatbot solutions are still built on rule-based logic, Telyx was built from scratch with an AI-first architecture. What does this mean? Telyx\'s AI assistant understands your business\'s product catalog, order history, and customer data to generate contextual and personalized responses. When a customer asks about their order status, the assistant accesses real-time shipping information and presents accurate data; it does not guess.' },
        { type: 'heading', text: 'Checklist for Choosing the Right Solution' },
        { type: 'paragraph', text: 'When choosing a chatbot solution for your e-commerce site, ask these questions: Can the solution seamlessly integrate with the e-commerce platform you use (Shopify, WooCommerce, etc.)? Is its natural language understanding capacity sufficient for your language? Can it manage real business processes like order tracking and customer verification? Does it allow you to manage all your channels (WhatsApp, email, web chat) from one place? Is the cost structure suitable for your business scale? A solution that positively answers these questions will take your e-commerce operations to the next level. Telyx is an integrated platform designed to meet all these criteria.' },
      ],
    },
  },
  'whatsapp-business-api-turkiye-2026': {
    category: { tr: 'Rehber', en: 'Guide' },
    title: {
      tr: 'Türkiye\'de WhatsApp Business API Nasıl Alınır? 2026 Adım Adım Rehberi',
      en: 'How to Get WhatsApp Business API in Turkey: 2026 Step-by-Step Guide',
    },
    excerpt: {
      tr: 'WhatsApp Business API\'yi Türkiye\'de almak için gereken her adımı, BSP seçimini, Meta Business Manager kurulumunu ve sık yapılan hataları detaylıca anlatıyoruz.',
      en: 'Every step required to get WhatsApp Business API in Turkey — choosing a BSP, Meta Business Manager setup, and common pitfalls.',
    },
    date: '2026-04-28',
    readTime: { tr: '10 dk', en: '8 min' },
    author: 'Telyx Ekibi',
    color: 'from-emerald-500 to-green-600',
    keywords: [
      'whatsapp business api türkiye',
      'whatsapp business api nasıl alınır',
      'whatsapp business solution provider',
      'meta business manager kurulum',
      'whatsapp business api fiyat',
      'whatsapp api başvuru',
      'türkçe whatsapp api rehberi',
    ],
    content: {
      tr: [
        { type: 'paragraph', text: 'WhatsApp Business API, 2026 itibarıyla Türk işletmelerin müşteri iletişiminde kullandığı en kritik altyapıya dönüştü. Ancak resmi API\'yi almak, normal WhatsApp Business uygulaması yüklemek kadar basit değil. Süreç birkaç teknik adım, doğrulama ve doğru bir BSP (Business Solution Provider) seçimini içeriyor. Bu rehberde sıfırdan başlayarak Türkiye\'de WhatsApp Business API almak için izlemeniz gereken her adımı, sık yapılan hataları ve onay sürelerini anlatıyoruz.' },
        { type: 'heading', text: 'WhatsApp Business API Nedir, Neden Önemlidir?' },
        { type: 'paragraph', text: 'WhatsApp Business API, Meta\'nın işletmelere sağladığı resmi programatik mesajlaşma arayüzüdür. Standart WhatsApp Business uygulamasının aksine ölçeklenebilirdir, otomatik şablon mesaj göndermeye izin verir, CRM ve chatbot entegrasyonlarına imkân tanır. 2026\'da Türk e-ticaret işletmelerinin yaklaşık yüzde 70\'i müşteri iletişiminde WhatsApp\'ı birinci sıraya koyuyor; ortalama mesaj açılma oranı yüzde 98 civarında. Bu sebeple API erişimi artık seçenek değil, zorunluluk seviyesinde.' },
        { type: 'heading', text: '1. Adım: Meta Business Manager Hesabı Açın ve İşletmeyi Doğrulayın' },
        { type: 'paragraph', text: 'Önce business.facebook.com adresinden bir Meta Business Manager hesabı oluşturmanız gerekiyor. Bu hesap altında şirketinizin yasal adı, vergi numarası ve adres bilgisini eksiksiz girmelisiniz. Ardından Meta\'nın işletme doğrulama sürecini başlatın; vergi levhası, faturanız veya hesap özetiniz gibi belgeler talep edilecek. Türkiye\'den başvuran işletmeler için doğrulama tipik olarak 2-5 iş günü sürüyor. Bu adım atlanırsa şablon onayları ve mesaj limiti yükseltmeleri sorun çıkarır.' },
        { type: 'heading', text: '2. Adım: Doğru BSP\'yi Seçin' },
        { type: 'paragraph', text: 'WhatsApp Business API\'ye doğrudan başvuramazsınız; Meta\'nın onayladığı bir Business Solution Provider üzerinden gitmeniz gerekiyor. BSP seçimi maliyet ve özellik bakımından kritik. Türkiye\'de hizmet veren BSP\'lerin çoğu mesaj başına yüksek komisyonlar alır ve template onay süreçlerinde geri bildirim sınırlıdır. Telyx, doğrudan Meta Cloud API\'siyle entegre çalışır ve aracısız bir altyapı sunar; mesaj başına ek komisyon yoktur, sadece WhatsApp\'ın kendi tarife yapısı uygulanır. BSP seçerken kontrol etmeniz gereken kriterler: mesaj başına ek ücret var mı, şablon yönetimi UI\'sı var mı, webhook yetenekleri ne, KVKK uyumlu veri saklama konumu (AB / Türkiye) sağlanıyor mu.' },
        { type: 'heading', text: '3. Adım: Telefon Numarasını API\'ye Bağlayın' },
        { type: 'paragraph', text: 'API kullanılacak numara, ya yepyeni bir iş hattı ya da var olan ama WhatsApp\'ta hesabı bulunmayan bir numara olmalı. Eğer mevcut bir kişisel WhatsApp\'ınız varsa önce o hesabı silmeniz gerekiyor. Numara onayı SMS veya sesli arama ile yapılır; Türkiye\'de operatörler arasında onay süresi 5-30 dakika arasında değişir. Bu adımdan sonra geri dönüş yoktur — numara artık sadece API üzerinden çalışır, normal WhatsApp uygulamasına giremezsiniz.' },
        { type: 'heading', text: '4. Adım: Mesaj Şablonlarını Hazırlayın' },
        { type: 'paragraph', text: 'API üzerinden müşteri size yazmadan ilk mesaj göndermek istiyorsanız (sepet kurtarma, randevu hatırlatma, kampanya), Meta\'nın onayladığı şablon mesajlar kullanmanız gerekiyor. Şablonlar; pazarlama, fayda (utility) ve doğrulama (authentication) olarak üç kategoriye ayrılır. Pazarlama şablonları en sıkı incelenir ve reddedilebilir. Onay genellikle 24-48 saat içinde gelir. Şablon yazarken dikkat edilmesi gereken noktalar: net fayda ifadesi, opt-out talimatı içermesi, müşteri hakkında bilgi içermemesi (kişiselleştirme {{1}} gibi parametre olarak yapılır).' },
        { type: 'heading', text: '5. Adım: Webhook ve Otomasyon Bağlantısını Kurun' },
        { type: 'paragraph', text: 'API mesajlaşmasının asıl gücü gelen mesajları işleyebilen webhook entegrasyonunda. Müşteri size yazdığında mesaj kendi sisteminize iletilir, AI ya da operatör yanıtı geri döner. Telyx kullananların bu adıma teknik bilgisi gerekmez — webhook ve AI bağlantısı kutudan çıkar. Kendi backend\'inizi kuruyorsanız, webhook URL\'sinin HTTPS olması, Meta\'nın imza doğrulamasını uygulayan bir endpoint olması ve yüksek trafikte bayağa çekilmemesi (failed delivery oranı %5\'in üzerine çıkarsa Meta API erişimini kısıtlayabilir) önemli.' },
        { type: 'heading', text: 'Sık Yapılan Hatalar ve Önlenmesi' },
        { type: 'paragraph', text: 'Birinci hata: Yanlış BSP seçimi. Düşük başlangıç fiyatı ile başlayan ama mesaj başına yüksek komisyon alan BSP\'ler aylık faturada sürpriz yaratır. İkinci hata: İşletme doğrulamasını eksik bilgiyle yapmak. Vergi numarası ve şirket adı Meta\'nın gördüğü resmi kayıtla eşleşmiyorsa süreç haftalarca uzar. Üçüncü hata: Şablon mesajlarda doğrudan promosyon yapmak; WhatsApp pazarlama şablonlarında çok katı kuralları var. Dördüncü hata: Onay sonrası mesaj limitini aşmak. Yeni numaralar 24 saat içinde 1.000 mesajla başlar; aktif kullanım ile zamanla 100.000\'e çıkabilir. Aşırı gönderim numara dondurmaya yol açar.' },
        { type: 'heading', text: 'Telyx İle Süreci Atlayın' },
        { type: 'paragraph', text: 'Yukarıdaki tüm adımları kendiniz yapmak, en az 1-2 hafta ve teknik bir ekip gerektirir. Telyx kullanıyorsanız, Meta Business Manager kurulumu hariç tüm süreci sizin için yönetiyoruz. Deneme planında 14 günlük ücretsiz erişim alır, kurulumu adım adım birlikte yaparız. Daha hızlı başlatmak için info@telyx.ai adresinden iletişime geçebilirsiniz.' },
      ],
      en: [
        { type: 'paragraph', text: 'WhatsApp Business API has become a critical infrastructure for Turkish businesses in 2026. However, getting access is more involved than installing the consumer app. The process requires Business Manager setup, identity verification, BSP selection, phone number registration and template approval. This guide walks through each step.' },
        { type: 'heading', text: 'Step 1: Meta Business Manager + Verification' },
        { type: 'paragraph', text: 'Open a Meta Business Manager account at business.facebook.com with your legal company name, tax number and address. Initiate Meta\'s business verification — typically takes 2-5 business days for Turkish businesses.' },
        { type: 'heading', text: 'Step 2: Choose Your BSP' },
        { type: 'paragraph', text: 'You cannot apply directly to Meta; you must go through a Business Solution Provider. Pick one without per-message commission, with template management UI, webhook capabilities and KVKK-compliant data storage. Telyx integrates directly with Meta Cloud API.' },
        { type: 'heading', text: 'Step 3: Phone Number Registration' },
        { type: 'paragraph', text: 'Use a fresh business line or a number not currently active in WhatsApp. Verification is via SMS or voice call; once registered the number can no longer be used in the consumer app.' },
        { type: 'heading', text: 'Step 4: Template Messages' },
        { type: 'paragraph', text: 'For outbound messaging (cart recovery, appointment reminders, campaigns), prepare Meta-approved templates. Three categories: marketing, utility, authentication. Approval typically takes 24-48 hours.' },
        { type: 'heading', text: 'Step 5: Webhooks and Automation' },
        { type: 'paragraph', text: 'Connect a webhook for inbound messages. Telyx wires this automatically; if you build your own backend, ensure HTTPS, signature verification and high availability.' },
      ],
    },
  },
  'ai-musteri-hizmetleri-roi-hesabi': {
    category: { tr: 'Strateji', en: 'Strategy' },
    title: {
      tr: 'AI Müşteri Hizmetlerinin ROI\'sini Nasıl Hesaplarsınız? Vaka Çalışması ile',
      en: 'How to Calculate AI Customer Service ROI: A Case Study Approach',
    },
    excerpt: {
      tr: 'AI müşteri hizmetleri yatırımının geri dönüşünü gerçek metriklerle hesaplama yöntemini ve örnek bir e-ticaret işletmesinin 12 aylık verilerini paylaşıyoruz.',
      en: 'How to calculate AI customer service ROI with real metrics, illustrated with 12 months of data from an e-commerce case study.',
    },
    date: '2026-04-22',
    readTime: { tr: '8 dk', en: '7 min' },
    author: 'Telyx Ekibi',
    color: 'from-[#000ACF] to-[#006FEB]',
    keywords: [
      'ai müşteri hizmetleri roi',
      'chatbot roi hesabı',
      'whatsapp chatbot dönüş hesabı',
      'müşteri hizmetleri otomasyon roi',
      'ai yatırım dönüşü',
      'chatbot maliyet analizi',
    ],
    content: {
      tr: [
        { type: 'paragraph', text: 'AI müşteri hizmetlerine yatırım yapmadan önce yöneticilerin ortak sorusu hep aynıdır: "Bu yatırımın geri dönüşü ne kadar olacak?" Cevap, görünenden çok daha hesaplanabilir. AI müşteri hizmetlerinin ROI\'si üç ana metrik üzerine kurulur: doğrudan operasyon maliyeti tasarrufu, dönüşüm artışı (sepet kurtarma, lead kalifikasyonu) ve müşteri sadakati. Bu yazıda gerçek bir e-ticaret vakasının 12 aylık verilerini kullanarak ROI hesaplama mantığını adım adım gösteriyoruz.' },
        { type: 'heading', text: 'ROI Formülü: Üç Bileşen' },
        { type: 'paragraph', text: 'Geleneksel ROI formülü ((Kazanç - Maliyet) / Maliyet) × 100 olsa da, AI müşteri hizmetlerinde "kazanç" tarafını üç kalem oluşturuyor. Birincisi tasarruf: AI çözdüğü her destek talebinde insan operatör maliyetini düşürür. İkincisi gelir artışı: sepet kurtarma kampanyaları, ürün önerisi ve hızlı sipariş takibi doğrudan satışı artırır. Üçüncüsü retansiyon değeri: müşteri memnuniyeti artınca lifetime value yükselir. Toplam fayda bu üçünün toplamıdır; maliyet ise sadece platform abonelik ücreti + entegrasyon zamanıdır.' },
        { type: 'heading', text: 'Vaka: Orta Ölçekli E-ticaret İşletmesi' },
        { type: 'paragraph', text: 'Aylık 4.500 sipariş alan, 2 destek temsilcisi olan bir e-ticaret işletmesini ele alalım. Telyx Pro planına geçişle birlikte 12 aylık verileri şu şekilde değişti. Aylık destek talebi 6.000\'den 6.300\'e çıktı (yüzde 5 büyüme); ancak bunların yüzde 72\'si AI tarafından çözüldü. Operatörler artık sadece karmaşık konularla ilgilendi; ortalama yanıt süresi 8 saatten 2 saate düştü. Sepet kurtarma WhatsApp şablonu 12 ay boyunca 14.220 ek sipariş getirdi (sepetleri terk eden kullanıcıların yüzde 18\'i geri döndü). Sipariş takibi otomasyonu sayesinde kargo şikâyetleri azaldı, NPS skoru 42\'den 64\'e yükseldi.' },
        { type: 'heading', text: 'Maliyet Tasarrufu Hesabı' },
        { type: 'paragraph', text: 'Aynı talep yükünü 100 yüzde insan operatörle karşılamak isteseniz 4 destek temsilcisi gerekirdi (mevcut 2\'ye ek 2). Türkiye\'de bir destek temsilcisinin yıllık brüt maliyeti (maaş + SGK + ekipman) 480.000 TL. 2 ek temsilci = yıllık 960.000 TL ek maliyet. Telyx Pro planı yıllık 89.988 TL (12 × 7.499). Doğrudan tasarruf = 870.012 TL/yıl.' },
        { type: 'heading', text: 'Gelir Artışı Hesabı' },
        { type: 'paragraph', text: 'Sepet kurtarma kampanyası 12 ayda 14.220 ek sipariş getirdi. Ortalama sipariş tutarı 850 TL ise ek gelir 12.087.000 TL. Bunun net karını yüzde 25 brüt marj üzerinden hesaplarsak (e-ticaret için tipik) 3.021.750 TL. Yani sadece bu tek özellik bile platform yatırımının 33 katı geri dönüş sağladı.' },
        { type: 'heading', text: 'Toplam ROI' },
        { type: 'paragraph', text: 'Maliyet tasarrufu (870.012 TL) + gelir katkısı (3.021.750 TL) = 3.891.762 TL toplam fayda. Yatırım 89.988 TL. ROI = ((3.891.762 - 89.988) / 89.988) × 100 = yüzde 4.224. Bu rakam ekstrem değil; büyük ölçekli e-ticaret işletmelerinde benzer ROI\'leri sürekli görüyoruz. Önemli olan sepet kurtarma, sipariş takibi ve kargo otomasyonunun aktif kullanılmasıdır.' },
        { type: 'heading', text: 'Kendi ROI\'nizi Nasıl Hesaplarsınız?' },
        { type: 'paragraph', text: 'Aşağıdaki dört rakamı toplayın: 1) Aylık destek talebi sayısı. 2) Mevcut talep başına insan operatör maliyeti (saat × ücret). 3) AI çözüm oranı (Telyx ortalama yüzde 65-75). 4) Sepet kurtarma / lead kalifikasyonu fırsatı (e-ticaretseniz aylık terk edilen sepet sayısı, B2B iseniz haftalık demo talep sayısı). Bu dört rakam ile basit bir ROI tahmini yapabilirsiniz. Telyx satış ekibi sektörünüze özel ROI tablosu hazırlamak için 15 dakikalık ücretsiz danışmanlık veriyor; info@telyx.ai üzerinden talep edebilirsiniz.' },
      ],
      en: [
        { type: 'paragraph', text: 'Before investing in AI customer service, executives always ask: "What\'s the ROI?" The answer is more measurable than it seems. AI customer service ROI rests on three pillars: direct cost savings, revenue uplift (cart recovery, lead qualification), and retention value. This article walks through a 12-month e-commerce case study.' },
        { type: 'heading', text: 'The ROI Formula' },
        { type: 'paragraph', text: 'The classic ((Gain - Cost) / Cost) × 100 formula applies, but "gain" has three components: cost savings from AI-resolved tickets, revenue uplift from cart recovery, and increased customer LTV from improved CSAT.' },
        { type: 'heading', text: 'Case: Mid-Sized E-Commerce' },
        { type: 'paragraph', text: 'A business with 4,500 monthly orders and 2 support agents moved to Telyx Pro. AI resolved 72% of tickets, dropping response time from 8 hours to 2. Cart recovery brought 14,220 extra orders over 12 months. NPS jumped from 42 to 64.' },
        { type: 'heading', text: 'Cost Savings + Revenue Uplift' },
        { type: 'paragraph', text: 'Without AI, two additional agents would cost ~960k TL/year. Telyx Pro is 90k TL/year. Cart recovery added 12.1M TL revenue (~3M TL net margin). Total benefit: ~3.9M TL on a 90k TL investment.' },
        { type: 'heading', text: 'Calculate Your Own' },
        { type: 'paragraph', text: 'Gather four numbers: monthly ticket volume, cost per ticket today, expected AI resolution rate (typically 65-75%), and abandoned cart count. With these you can sketch a ROI estimate.' },
      ],
    },
  },
  'kvkk-uyumlu-chatbot-rehberi': {
    category: { tr: 'Güvenlik', en: 'Security' },
    title: {
      tr: 'KVKK Uyumlu Chatbot Nasıl Tasarlanır? Türk İşletmeler İçin Tam Rehber',
      en: 'How to Design a KVKK-Compliant Chatbot: A Complete Guide for Turkish Businesses',
    },
    excerpt: {
      tr: 'Chatbot\'unuzun KVKK uyumlu olması için gerekli teknik ve hukuki adımları, müşteri rıza yönetimini ve veri saklama ilkelerini detaylıca inceliyoruz.',
      en: 'Technical and legal requirements for KVKK-compliant chatbots — consent management, data retention principles, and architectural considerations.',
    },
    date: '2026-04-15',
    readTime: { tr: '9 dk', en: '7 min' },
    author: 'Telyx Ekibi',
    color: 'from-[#051752] to-[#006FEB]',
    keywords: [
      'kvkk uyumlu chatbot',
      'kvkk chatbot rehberi',
      'türk işletmeler kvkk',
      'müşteri verisi koruma chatbot',
      'gdpr uyumlu ai',
      'kvkk veri saklama chatbot',
      'müşteri rıza yönetimi',
    ],
    content: {
      tr: [
        { type: 'paragraph', text: 'Türkiye\'de bir chatbot çalıştırmak istiyorsanız, KVKK (Kişisel Verilerin Korunması Kanunu) ile uyumluluk pazarlık edilemez bir gerekliliktir. KVKK Kurulu son yıllarda chatbot operatörlerine ciddi cezalar kesti; özellikle açık rıza alınmaması, yurt dışına veri aktarımı ve veri saklama sürelerinin tanımsızlığı gibi konularda. Bu rehberde chatbot mimarinizi KVKK uyumlu kılmak için izlemeniz gereken teknik ve hukuki adımları detaylıca inceliyoruz.' },
        { type: 'heading', text: 'KVKK\'nın Chatbot Mimarisine Yansıyan Beş İlkesi' },
        { type: 'paragraph', text: 'KVKK\'nın altıncı maddesinde tanımlanan beş ilke chatbot mimarisinin temelini oluşturur. Birincisi: hukuka ve dürüstlük kurallarına uygun işleme. Müşteri size yazdığında verisinin nasıl kullanılacağını şeffaf bilmelidir. İkincisi: amaca uygunluk. Sipariş takibi için topladığınız telefon numarasını pazarlama için kullanamazsınız. Üçüncüsü: amaçla bağlantılılık ve sınırlılık. Müşterinin sadece soruyu cevaplamaya yetecek kadar bilgi tutun. Dördüncüsü: doğru ve güncel olma. Yanlış veri tutmak da ihlal sayılır. Beşincisi: belirli süre saklama. Müşteri verisi sonsuza dek saklanmaz; bir saklama süresi tanımlanmalıdır.' },
        { type: 'heading', text: 'Açık Rıza Nasıl Alınır?' },
        { type: 'paragraph', text: 'Chatbot ilk kez bir müşteriyle iletişime geçtiğinde rıza metni gösterilmesi şarttır. WhatsApp\'ta bu, ilk şablon mesajının sonunda "Mesajınız Telyx tarafından işlenmektedir, gizlilik politikamız: telyx.ai/privacy" gibi kısa bir cümle olmalıdır. Web chat widget\'larda widget açılırken kabul kutusu gösterilebilir. Açık rıza özgür iradeye dayalı, açıklanmış ve belirli bir konu hakkında olmalıdır. Genel "kabul ediyorum" bandolu yetersizdir; "destek talebimi cevaplamak için verilerimin işlenmesini kabul ediyorum" gibi spesifik olmalıdır. Rıza her zaman geri çekilebilir ve geri çekme arayüzü kolay erişilebilir olmalıdır.' },
        { type: 'heading', text: 'Veri Saklama: Ne Kadar Süre Tutmalısınız?' },
        { type: 'paragraph', text: 'KVKK\'nın açıkça belirtmediği ama Kurul kararlarından çıkan kural: amacı kalmadığı an veri silinmelidir. Müşteri sohbet kaydı için pratik bir süre 12-24 ay arasıdır; bu sürenin sonunda otomatik anonimleştirme veya silme süreci işlemelidir. İletişim bilgisi (telefon, e-posta) için müşterinin işletmenizle ilişkisi sürdüğü sürece saklanabilir; ilişki bittikten sonra (kayıt iptali, hesap silme talebi) en geç 6 ay içinde imha edilmesi önerilir. Telyx\'te varsayılan veri saklama süreleri yapılandırılabilir.' },
        { type: 'heading', text: 'Yurt Dışı Veri Transferi Riski' },
        { type: 'paragraph', text: 'KVKK\'nın en yanılgıya neden olan maddesi yurt dışı transferdir. Eğer chatbot platformunuz veriyi AB veya ABD sunucularında işliyorsa (ki birçok büyük chatbot platformu yapıyor), açık rıza dışında ek bir hukuki temel gereklidir. Bu temel ya KVKK\'nın yeterli korumayı tanıdığı bir ülke listesinde olmak (henüz bu liste yayımlanmadı) ya da müşteriyle imzalı bir taahhüt olabilir. Pratik çözüm: AB veri saklama yapılandırması veya tercihen Türkiye\'de barındırılan bir altyapı seçmek. Telyx, AB sunucularında saklama seçeneği sunar ve Türkiye veri saklama opsiyonu Pro plan ile mevcuttur.' },
        { type: 'heading', text: 'Hassas Veri ve AI Yanıtı Sınırları' },
        { type: 'paragraph', text: 'Sağlık, cinsel hayat, dini inanç gibi özel nitelikli kişisel veriler KVKK\'da daha sıkı korunur. Bir klinik chatbot\'unun hastanın hastalığını paylaşması veya bir dini topluluğun chatbot\'unun üye bilgilerini saklaması yasak değildir, ama "açık rıza" + "bunun dışında bir hukuki sebep" çift koşulu gerekir. AI tarafı için pratik kural: özel nitelikli veri tespit edildiğinde otomatik olarak insan operatör onayı moduna geçmek. Telyx semantic detection ile bunu yapabilir.' },
        { type: 'heading', text: 'Müşteri Hakları: Erişim, Silme, Düzeltme' },
        { type: 'paragraph', text: 'Müşterilerinizin KVKK\'da tanımlanan altı hakkı vardır: bilgi alma, erişim, düzeltme, silme, işlemenin durdurulması ve veri taşınabilirliği. Chatbot mimarinizde bu hakları operasyonel olarak nasıl karşılayacağınızı önceden tanımlamanız gerekir. Müşteri "verilerimi silin" dediğinde silme süreci otomatikleşmiş olmalıdır; manuel olarak yapılırsa hata riski yüksektir.' },
        { type: 'heading', text: 'Kontrol Listesi: KVKK Uyumluluğu Doğrulama' },
        { type: 'paragraph', text: 'Şu noktaları kontrol edin: 1) İlk mesajda rıza metni gösteriliyor mu? 2) Gizlilik politikası linki çalışıyor mu? 3) Veri saklama süresi tanımlı mı ve otomatik silme çalışıyor mu? 4) Yurt dışı transfer riski var mı, varsa hukuki temel ne? 5) Özel nitelikli veri tespiti aktif mi? 6) Müşteri silme talebine kaç saatte yanıt veriyorsunuz? Telyx tüm bu noktaları platform seviyesinde standartlaştırarak gelir.' },
      ],
      en: [
        { type: 'paragraph', text: 'If you operate a chatbot in Turkey, KVKK compliance is non-negotiable. The KVKK Authority has issued significant penalties for missing consent, undefined retention periods and improper cross-border transfers. This guide outlines the technical and legal steps to make your chatbot architecture compliant.' },
        { type: 'heading', text: 'Five Core Principles' },
        { type: 'paragraph', text: 'Article 6 of KVKK defines five principles: lawful processing, purpose limitation, data minimization, accuracy, and time-bound retention. Each must be reflected in your chatbot architecture.' },
        { type: 'heading', text: 'Explicit Consent' },
        { type: 'paragraph', text: 'On first contact, show consent text. On WhatsApp it can be a short line at the end of the first template message; on web chat, a tickbox. Consent must be specific and revocable.' },
        { type: 'heading', text: 'Data Retention' },
        { type: 'paragraph', text: 'A practical chat retention period is 12-24 months with automatic anonymization or deletion at end-of-life. Contact data may be kept while the customer relationship exists.' },
        { type: 'heading', text: 'Cross-Border Transfers' },
        { type: 'paragraph', text: 'If your chatbot processes data outside Turkey, additional legal grounds beyond explicit consent may be required. Prefer EU-region or Turkey-hosted infrastructure. Telyx supports both.' },
        { type: 'heading', text: 'Compliance Checklist' },
        { type: 'paragraph', text: 'Verify: consent text on first message, working privacy policy link, defined retention with auto-deletion, sensitive data detection, customer rights workflow (access, deletion, correction).' },
      ],
    },
  },
  'sesli-ai-vs-geleneksel-cagri-merkezi': {
    category: { tr: 'Karşılaştırma', en: 'Comparison' },
    title: {
      tr: 'Sesli AI Çağrı Merkezi vs. Geleneksel Çağrı Merkezi: 2026 Karşılaştırması',
      en: 'AI Voice Call Center vs. Traditional Call Center: 2026 Comparison',
    },
    excerpt: {
      tr: 'Sesli AI çağrı merkezleri ile geleneksel insan operatörlü çağrı merkezlerini maliyet, kalite, ölçeklenebilirlik ve müşteri deneyimi açısından karşılaştırıyoruz.',
      en: 'Comparing AI voice call centers and human-operated traditional centers across cost, quality, scalability, and customer experience.',
    },
    date: '2026-04-10',
    readTime: { tr: '7 dk', en: '6 min' },
    author: 'Telyx Ekibi',
    color: 'from-[#000ACF] to-[#00C4E6]',
    keywords: [
      'sesli ai çağrı merkezi',
      'ai vs geleneksel çağrı merkezi',
      'çağrı merkezi karşılaştırma',
      'voice ai türkiye',
      'çağrı merkezi otomasyon',
      'sesli yapay zeka asistan',
    ],
    content: {
      tr: [
        { type: 'paragraph', text: '2026 itibarıyla "AI sesli çağrı merkezi" terimi yepyeni bir teknoloji olmaktan çıktı; pek çok orta ve büyük ölçekli işletmenin operasyon altyapısının normal bir parçası haline geldi. Ama küçük ve orta işletmeler hâlâ kararsız: geleneksel çağrı merkeziyle devam mı etmeli, yoksa sesli AI\'ya mı geçmeli? Bu yazıda dört kritik kriter üzerinden gerçekçi bir karşılaştırma sunuyoruz: maliyet, hizmet kalitesi, ölçeklenebilirlik ve müşteri deneyimi.' },
        { type: 'heading', text: 'Maliyet: Sabit Ölçek vs. Esneklik' },
        { type: 'paragraph', text: 'Geleneksel çağrı merkezinde maliyet doğrusal artıyor. Bir temsilcinin yıllık brüt maliyeti (maaş, SGK, eğitim, ekipman, yönetim payı) Türkiye\'de ortalama 480.000 TL. 8 saatlik vardiyada bir temsilci ortalama 60-90 çağrı yanıtlıyor. 24/7 destek için en az 6 temsilci gerekiyor — yıllık 2.880.000 TL. AI sesli platformda durumun şekli farklı: aylık taban abonelik (Telyx\'te 7.499 TL ile başlıyor) + dakika başına aşım ücreti (23 TL/dk). 1.000 dakika kullanım ayda 23.000 TL ek demek. Aynı 24/7 hizmeti AI ile sağlamak yıllık 350-500.000 TL aralığında kalır — geleneksel modelin yüzde 15-17\'si.' },
        { type: 'heading', text: 'Kalite: Hız vs. Empati' },
        { type: 'paragraph', text: 'Geleneksel modelin avantajı insan empatisi. Karmaşık şikâyet, hassas yas durumu, yatıştırma gerektiren konularda insan temsilciler hâlâ üstün. AI\'nın avantajı ise hız ve tutarlılık. AI ortalama 0.8 saniyede yanıt verir; insan ise telefonun açılması için ortalama 2-4 dakika bekletir (Türkiye ortalaması). AI hiç yorulmaz, akşam saatlerinde hizmet kalitesi düşmez, bayram günlerinde çalışmaktan şikayet etmez. Pratik çözüm: birinci basamak AI, karmaşık olunca handoff. Bu hibrit model, hem hızı hem empatiyi sağlar.' },
        { type: 'heading', text: 'Ölçeklenebilirlik: Eşzamanlı Çağrı Sayısı' },
        { type: 'paragraph', text: 'Geleneksel modelde "10 eşzamanlı çağrı" demek "10 temsilci" demek. Bayram öncesi yığılma yaşayan e-ticaret işletmeleri, ek temsilci için ayda 100.000 TL ödüyor — sonra bayram bitince ekip eve gönderiliyor. AI sesli platformda eşzamanlı çağrı kapasitesi yazılım üzerinden anında ayarlanır. Bayram öncesi 50 eşzamanlı çağrıya çıkmak teknik olarak bir tıklama. Bu esneklik, sezonluk işletmeler için kritik: oteller, restoranlar, eğitim kurumları, satış kampanyaları yapan markalar.' },
        { type: 'heading', text: 'Müşteri Deneyimi: Algı Değişiyor' },
        { type: 'paragraph', text: 'Beş yıl önce sesli AI çağrı yanıtladığında müşteri rahatsız olurdu. 2026\'da ise AI\'nın sesi o kadar doğal ki çoğu müşteri farkı anlamıyor. Önemli olan açıklamanın doğru zamanda yapılması: AI\'nın yapay zeka olduğunu açıkça belirtmek (gizlemek KVKK\'ya da aykırı), insan operatörü ne zaman talep edebileceklerini söylemek. Bu şeffaflıkla birlikte müşteri memnuniyet skorları AI\'lı sistemlerde geleneksel sistemlere yakın, çoğu zaman daha yüksek çıkıyor — çünkü bekleme yok, çözüm hızlı.' },
        { type: 'heading', text: 'Karar Matrisi: Hangi İşletmeye Hangisi?' },
        { type: 'paragraph', text: 'AI sesli çağrı merkezi şu durumlarda açık ara üstün: çağrı hacmi yüksek (>2.000/ay), sezonluk dalgalanma var, çağrıların büyük kısmı tekrar eden konularda (sipariş, randevu, fatura, kargo), 24/7 hizmet zorunlu. Geleneksel model şu durumlarda daha mantıklı: çağrı hacmi düşük (<500/ay), her çağrı yüksek değerli ve uzun (B2B kurumsal satış, hukuki danışmanlık), insan ilişkisi temel ürün değeri. Çoğu işletme için doğru çözüm hibrit: AI birinci basamak + insan ikinci basamak.' },
        { type: 'heading', text: 'Geçiş Yapıyorsanız Dikkat Edilecekler' },
        { type: 'paragraph', text: 'Geleneksel modelden AI sesli sisteme geçiş aniden olmaz. İdeal yol şu: önce ortalama bir aylık çağrı verisini analiz edin (hangi konular sık geliyor); sık konuları AI\'ya öğretin; ilk ay AI\'yı paralel çalıştırın (insan da bağlı olsun) ve hata oranını ölçün; ikinci aydan itibaren AI birinci basamak, insan ikinci basamak olsun. Telyx Pro planı geçiş döneminde phantom-deploy modu sunar; AI önce gözlemci olarak çalışır, sonra aktif yanıtlamaya geçer.' },
      ],
      en: [
        { type: 'paragraph', text: 'In 2026, "AI voice call center" is no longer a futuristic term — it is now part of operations stack for many mid-to-large businesses. But small and mid-sized companies still hesitate. This article compares AI voice and traditional human call centers across four critical dimensions.' },
        { type: 'heading', text: 'Cost: Linear vs. Elastic' },
        { type: 'paragraph', text: 'Traditional centers cost linearly with headcount. AI platforms have a low base subscription plus per-minute overage, scaling 5-7x cheaper for 24/7 operations.' },
        { type: 'heading', text: 'Quality: Speed vs. Empathy' },
        { type: 'paragraph', text: 'AI excels at speed and consistency; humans excel at empathy and complex situations. The hybrid (AI first-line + human escalation) captures both.' },
        { type: 'heading', text: 'Scalability' },
        { type: 'paragraph', text: 'AI scales concurrent calls instantly via software. Traditional models require hiring and training. Critical for seasonal businesses.' },
        { type: 'heading', text: 'When AI Wins, When Traditional Wins' },
        { type: 'paragraph', text: 'AI wins for high-volume, repetitive, 24/7 needs. Traditional wins for low-volume, high-touch, relationship-driven calls. Most businesses benefit from a hybrid.' },
      ],
    },
  },
  'restoran-no-show-azaltma-stratejisi': {
    category: { tr: 'Restoran', en: 'Restaurant' },
    title: {
      tr: 'Restoran No-Show Oranını %50 Azaltmak: WhatsApp Hatırlatma Stratejisi',
      en: 'Cut Restaurant No-Shows by 50%: A WhatsApp Reminder Strategy',
    },
    excerpt: {
      tr: 'Restoranlarda boş kalan rezervasyonlar (no-show) ciddi gelir kaybı yaratıyor. WhatsApp hatırlatma akışlarıyla bu oranı yarıya nasıl indireceğinizi anlatıyoruz.',
      en: 'No-shows cost restaurants real revenue. Here is how a WhatsApp reminder workflow can cut them in half.',
    },
    date: '2026-04-05',
    readTime: { tr: '6 dk', en: '5 min' },
    author: 'Telyx Ekibi',
    color: 'from-orange-500 to-red-500',
    keywords: [
      'restoran no-show',
      'rezervasyon hatırlatma whatsapp',
      'restoran rezervasyon takibi',
      'no-show azaltma',
      'restoran whatsapp otomasyon',
      'masa rezervasyonu hatırlatma',
    ],
    content: {
      tr: [
        { type: 'paragraph', text: 'Türkiye\'de restoranların ortalama no-show oranı yüzde 18-25 arasında. Yani her 4 rezervasyondan bir tanesi gelmiyor. Hafta sonu yoğun cumartesi akşamı için bu oran daha da yükselebiliyor. Boş kalan masa, sadece o akşamki gelir kaybı değil; çünkü genellikle bekleme listesindeki başka müşterilere "dolu" denerek de iki kez gelir kaybı yaşanıyor. Bu yazıda WhatsApp hatırlatma stratejisi ile no-show\'ları yüzde 50\'ye kadar azaltmanın somut yolunu anlatıyoruz.' },
        { type: 'heading', text: 'No-Show\'un Ardındaki Davranışsal Sebepler' },
        { type: 'paragraph', text: 'Müşteri rezervasyon yapıp gelmediğinde ardındaki sebep çoğunlukla kötü niyet değil; unutkanlık, programın değişmesi veya rahat iptal etme imkânının olmaması. Telefon araması ya da web formla rezervasyon yapan müşteri, iptal etmek için aynı yöntemi kullanmak zorunda kalıyor; bu zaman alıyor ve "boş ver, gitmem yeter" diyerek gitmemeyi tercih ediyor. WhatsApp\'ta iptal süreci tek tıkla gerçekleştiğinde, müşteri "iptal" demek yerine sessizce kaybolmuyor.' },
        { type: 'heading', text: 'Üç Aşamalı Hatırlatma Akışı' },
        { type: 'paragraph', text: 'En etkili akış üç aşamalıdır. Birinci aşama: rezervasyon onayı (rezervasyon yapılır yapılmaz). "Sayın {{ad}}, {{tarih}} {{saat}} için {{kişi sayısı}} kişilik rezervasyonunuz onaylandı. İptal etmek için ‘İPTAL\' yazın." İkinci aşama: bir gün önce hatırlatma. "Yarın {{saat}} rezervasyonunuzu hatırlatmak isteriz. Geliyor musunuz? EVET / İPTAL" Üçüncü aşama: 2 saat önce final teyit (sadece evet diyenlere gerekirse). Bu üç aşamalı yapı, müşteriye iptal etme fırsatını üç farklı zamanda sunar.' },
        { type: 'heading', text: 'AI\'nın Rolü: İptal Akışını Akıllı Yönetmek' },
        { type: 'paragraph', text: 'Müşteri "iptal" yazdığında AI yapacağı: rezervasyonu sistemden silmek, alternatif tarih önerebilmek, beklemedeki bir başka müşteriye o saati teklif etmek. Bu üç aksiyon manuel olarak yapılırsa restoranınızda ek bir kişi-saati harcar. AI ile birkaç saniye içinde tamamlanır. Telyx\'te yedek liste otomasyonu var: iptal edilen masa beklemede olan ilk müşteriye anında WhatsApp ile sunulur, "Bu saat için hazır masamız oldu, ister misiniz?" diye sorar.' },
        { type: 'heading', text: 'Vaka: 80 Kişilik İstanbul Restoranı' },
        { type: 'paragraph', text: '80 kişilik bir restoranda yıllık 4.800 rezervasyon (haftada ortalama 92). No-show oranı yüzde 22 = yıllık 1.056 boş masa. Ortalama tablo değeri 1.200 TL alındığında yıllık kayıp 1.267.200 TL. WhatsApp hatırlatma akışına geçiş sonrası no-show oranı yüzde 11\'e düştü; iptaller 480 oldu, ama 220\'si beklemede olan müşterilere yönlendirilerek doldurulabildi. Net kayıp 260 masaya indi, yıllık kayıp 312.000 TL\'ye düştü. Tasarruf 955.000 TL. WhatsApp kampanya altyapı maliyeti yıllık 90.000 TL. Net fayda 865.000 TL.' },
        { type: 'heading', text: 'Pratik Uygulama: Hangi Şablonlar Onaylanır?' },
        { type: 'paragraph', text: 'Meta\'nın WhatsApp şablon onay sürecinde "rezervasyon onayı" ve "rezervasyon hatırlatması" UTILITY (fayda) kategorisinde değerlendirilir; onay genellikle 24 saat içinde gelir. Şablonlarda dikkat: kişiselleştirilebilir alan ({{1}}, {{2}}) net olmalı, müşteri opt-out talimatı içermeli, abartılı emojiler ve büyük harflerle yazma onayı geciktirebilir. Telyx\'te şablon kütüphanesi hazır; restoran modülünü seçtiğinizde otomatik olarak onaylı şablonlar geliyor.' },
      ],
      en: [
        { type: 'paragraph', text: 'Average restaurant no-show rates in Turkey range from 18-25%. On weekend prime time, it can be even higher. A no-show is not just lost revenue for that night; it can also mean rejected waitlist customers. Here is how a WhatsApp reminder workflow halves no-shows.' },
        { type: 'heading', text: 'Behavioral Reasons' },
        { type: 'paragraph', text: 'Most no-shows are not malicious. They happen because cancellation friction is too high. WhatsApp removes that friction.' },
        { type: 'heading', text: 'Three-Stage Reminder Workflow' },
        { type: 'paragraph', text: 'Confirm at booking. Remind one day before with a one-tap cancel option. Final confirm 2 hours before. Each stage gives the customer a low-effort cancel path.' },
        { type: 'heading', text: 'Auto-Refill Cancelled Slots' },
        { type: 'paragraph', text: 'When AI handles a cancellation, it can offer the slot to a waitlisted customer instantly via WhatsApp.' },
        { type: 'heading', text: 'Case Study' },
        { type: 'paragraph', text: 'An 80-seat Istanbul restaurant cut no-shows from 22% to 11% with this workflow, recovering ~ 955k TL annually after subtracting the platform cost.' },
      ],
    },
  },
  'instagram-dm-ai-reklam-roi': {
    category: { tr: 'Sosyal Medya', en: 'Social Media' },
    title: {
      tr: 'Instagram DM\'lerini AI ile Yanıtlayarak Reklam Bütçenizden 2x Daha Fazla Verim Alın',
      en: 'Get 2x More From Your Instagram Ad Budget With AI DM Responses',
    },
    excerpt: {
      tr: 'Instagram reklamlarından gelen DM\'lere yapay zeka ile saniyeler içinde yanıt vermek, dönüşüm oranını ve reklam ROI\'sini nasıl iki katına çıkarıyor?',
      en: 'Why responding to Instagram ad DMs in seconds with AI doubles conversion rate and ad ROI.',
    },
    date: '2026-03-30',
    readTime: { tr: '6 dk', en: '5 min' },
    author: 'Telyx Ekibi',
    color: 'from-pink-500 via-red-500 to-yellow-500',
    keywords: [
      'instagram dm ai',
      'instagram reklam roi',
      'instagram dm chatbot',
      'meta ads dm dönüşüm',
      'instagram lead toplama',
      'instagram satış otomasyonu',
    ],
    content: {
      tr: [
        { type: 'paragraph', text: 'Instagram\'da reklam yapan herkes aynı manzarayı biliyor: kampanya yayına girer, ilk birkaç saatte onlarca DM gelir, ekip yanıt vermeye yetişemez, gelen sorular kaybolur, sıcak lead\'ler soğur. Aylık 50.000 TL bütçe ile çalışan bir e-ticaret markasının iç verisinde bunu net görüyoruz: reklamdan gelen DM\'lerin yüzde 60\'ı ilk 30 dakika içinde yanıtlanmazsa müşteriye dönüşmüyor. Bu yazıda AI ile DM yanıtlamanın matematiğini ve uygulamayı anlatıyoruz.' },
        { type: 'heading', text: 'Niye İlk 30 Dakika Bu Kadar Kritik?' },
        { type: 'paragraph', text: 'Instagram\'da müşteri DM atarken aktif satın alma niyetinde oluyor. Reklam görüyor, ürünü beğeniyor, "Stokta var mı?" yazıyor. Eğer aynı akşam veya sabah yanıt verirseniz büyük ihtimalle satışı kaybediyorsunuz. Çünkü o müşteri gece yatmadan önce 5 marka daha tarıyor; yarın yine aynı niyetle gelmeyecek. Hızlı yanıt vermek satış kapama oranını ortalama yüzde 80 artırıyor.' },
        { type: 'heading', text: 'AI Yanıtın Üç Avantajı' },
        { type: 'paragraph', text: 'Birinci avantaj: yanıt süresi. AI ortalama 2-5 saniyede yanıt verir; insan ekip için en iyi durumda 5-15 dakika. İkinci avantaj: 7/24 hizmet. Reklam gece yarısı bile çalışıyor; AI da öyle. Üçüncü avantaj: kalifikasyon. AI lead\'in ilgi alanını, bütçesini, hangi şehirden olduğunu sorgulayabilir; bu sayede satış ekibine sadece sıcak lead\'ler iletilir.' },
        { type: 'heading', text: 'AI Lead Kalifikasyonu Nasıl Çalışır?' },
        { type: 'paragraph', text: 'Müşteri "stokta var mı?" sorduğunda AI önce ürünü doğrular, stoğu kontrol eder. Sonra alıcı niyetini netleştirmek için "size en uygun rengi/bedeni öneren bir bağlantı yollayayım mı?" gibi sorular sorar. Müşterinin yanıtlarına göre AI etiketler atar: "yüksek ilgili", "fiyat hassas", "şehir Ankara", "kadın seyirci". Bu etiketler Telyx\'ten CRM\'e geçer ve satış ekibi sadece "yüksek ilgili" lead\'lere odaklanır. Soğuk lead\'lere ise AI follow-up mesajı gönderir; örneğin 3 gün sonra "indirimli fiyatla ilgilenir misiniz?"' },
        { type: 'heading', text: 'Reklam ROI Hesabı' },
        { type: 'paragraph', text: 'Aylık 50.000 TL Instagram bütçeli bir markanın eski sürecinde 1.200 DM geliyordu, %15 dönüşümle 180 satış yapılıyordu (ortalama satış 850 TL = 153.000 TL ciro). AI DM yanıt sistemine geçiş sonrası: aynı 1.200 DM\'ye 5 saniyede yanıt verildi, dönüşüm yüzde 30\'a çıktı = 360 satış (306.000 TL ciro). Reklam bütçesi aynı, hatta öyle ki — gelir iki katına çıktı. Telyx Starter plan aylık 2.499 TL — yani aylık ek maliyet bütçenin yüzde 5\'i, ama gelir yüzde 100 arttı.' },
        { type: 'heading', text: 'Story Reklamlardan Story Sticker\'a Akış' },
        { type: 'paragraph', text: 'Instagram\'da Story reklamlardan gelen DM\'ler, feed reklamlarından gelenlere göre yüzde 25 daha sıcak. Çünkü Story\'de görülen ürünü hatırlama oranı daha yüksek. AI bu lead\'leri Story reklam etiketiyle özel akışa alabilir; "Story\'mizden gelmişsiniz" mesajıyla başlar, daha samimi tonla devam eder. Story sticker\'lardan (ör. "Sorularınız var mı?" sticker) gelen DM\'ler ise tamamen ücretsiz; AI bu kanalı tamamen organik lead toplama mecrası olarak kullanabilir.' },
        { type: 'heading', text: 'Uyarı: Spam Görünmemek İçin' },
        { type: 'paragraph', text: 'Meta, Instagram\'da otomatik mesajlaşmayı izliyor. Aşırı kişiselleştirilmiş ya da çok hızlı seri mesajlar (3 saniyede 5 mesaj) spam olarak değerlendirilebilir. AI yanıt akışında dikkat edilecek: ilk yanıt 3-10 saniye gecikmeli olabilir (insan hızında), uzun yanıtları 2-3 mesaja böl, müşterinin yazdığı dilde yanıtla. Telyx\'in spam-prevention katmanı bu kuralları otomatik uygular.' },
      ],
      en: [
        { type: 'paragraph', text: 'Anyone who runs Instagram ads knows the picture: a campaign goes live, dozens of DMs arrive, the team cannot keep up, hot leads cool off. Internal data from a 50k TL/month e-commerce brand shows that DMs not answered within 30 minutes convert at 60% lower rates. AI DM response changes the math.' },
        { type: 'heading', text: 'Why The First 30 Minutes' },
        { type: 'paragraph', text: 'Instagram DMs come with active buying intent. Same-day delays cost the sale because customers compare 5+ brands before sleeping.' },
        { type: 'heading', text: 'Three Advantages' },
        { type: 'paragraph', text: 'AI reply time is 2-5 seconds. AI works 24/7. AI qualifies leads, passing only warm ones to sales.' },
        { type: 'heading', text: 'ROI Calculation' },
        { type: 'paragraph', text: 'A 50k TL monthly Instagram ad budget converted 180 sales (153k TL revenue) before AI. With AI DM response, conversion doubled to 360 sales (306k TL revenue) — same ad budget.' },
        { type: 'heading', text: 'Avoiding Spam Flags' },
        { type: 'paragraph', text: 'Meta watches automated messaging. Use 3-10 second response delays, split long messages into chunks, match customer language. Telyx applies these rules automatically.' },
      ],
    },
  },
};

export const BLOG_SLUGS = Object.keys(BLOG_POSTS);

export function getBlogPost(slug) {
  return BLOG_POSTS[slug] || null;
}

export function getRelatedSlugs(currentSlug, limit = 3) {
  return BLOG_SLUGS.filter((s) => s !== currentSlug).slice(0, limit);
}
