'use client';

import React, { useEffect, useState } from 'react';
import PageIntro from '@/components/PageIntro';
import EmptyState from '@/components/EmptyState';
import { getPageHelp } from '@/content/pageHelp';
import { useLanguage } from '@/contexts/LanguageContext';
import { toast } from '@/lib/toast';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  AlertCircle,
  AlertTriangle,
  CheckCircle2,
  RefreshCw,
  Sparkles,
  XCircle,
} from 'lucide-react';
import { useSikayetvarStatus } from '@/hooks/useIntegrations';
import {
  useApproveComplaintThread,
  useComplaintSettings,
  useComplaintStats,
  useComplaintThreads,
  useEditComplaintThread,
  useRejectComplaintThread,
  useUpdateComplaintSettings,
} from '@/hooks/useComplaints';

function getComplaintsCopy(locale) {
  const isTr = locale === 'tr';

  return {
    title: isTr ? 'Şikayet Yönetimi' : 'Complaint Management',
    subtitle: isTr
      ? 'Şikayetleri içeri alın, AI taslakları üretin ve manuel onayla platforma gönderin.'
      : 'Import complaints, generate AI drafts, and send them after manual approval.',
    emptyTitle: isTr ? 'Şikayetvar entegrasyonu bağlı değil' : 'Sikayetvar integration is not connected',
    emptyDescription: isTr
      ? 'Önce Entegrasyonlar sayfasından Şikayetvar tokenınızı bağlayın. Sistem açık şikayetleri çekip AI taslaklarını burada gösterecek.'
      : 'Connect your Sikayetvar token from the Integrations page first. The system will pull open complaints and show AI drafts here.',
    stats: {
      total: { title: isTr ? 'Toplam şikayet' : 'Total complaints', hint: isTr ? 'Sistemdeki tüm kayıtlar' : 'All records in the system' },
      todayTotal: { title: isTr ? 'Bugün gelen' : 'Received today', hint: isTr ? 'Bugün açılan yeni kayıtlar' : 'New records opened today' },
      pending: { title: isTr ? 'Onay bekleyen' : 'Pending approval', hint: isTr ? 'Gönderim öncesi sıradakiler' : 'Items waiting before posting' },
      posted: { title: isTr ? 'Gönderilen' : 'Posted', hint: isTr ? 'Platforma gönderilen yanıtlar' : 'Replies posted to the platform' },
    },
    filters: {
      search: isTr ? 'Ara' : 'Search',
      searchPlaceholder: isTr ? 'Başlık, müşteri adı veya şikayet metni' : 'Title, customer name, or complaint text',
      status: isTr ? 'Durum' : 'Status',
      statusPlaceholder: isTr ? 'Durum' : 'Status',
      all: isTr ? 'Tümü' : 'All',
      pending: isTr ? 'Bekleyen' : 'Pending',
      posted: isTr ? 'Gönderilen' : 'Posted',
      rejected: isTr ? 'Reddedilen' : 'Rejected',
      error: isTr ? 'Hatalı' : 'Error',
      fromDate: isTr ? 'Başlangıç' : 'Start',
      toDate: isTr ? 'Bitiş' : 'End',
    },
    card: {
      openedAt: isTr ? 'Açılış' : 'Opened',
      platform: 'Sikayetvar',
      noTitle: isTr ? 'Şikayet başlığı yok' : 'No complaint title',
      customerFallback: isTr ? 'Müşteri' : 'Customer',
      cityFallback: isTr ? 'Şehir bilgisi yok' : 'No city information',
      complaint: isTr ? 'Şikayet' : 'Complaint',
      aiDraft: isTr ? 'AI taslağı' : 'AI draft',
      noDraft: isTr ? 'Henüz cevap üretilmedi' : 'No answer has been generated yet',
      openOnPlatform: isTr ? 'Şikayeti platformda aç' : 'Open complaint on platform',
      approveAndSend: isTr ? 'Onayla ve Gönder' : 'Approve and Send',
      edit: isTr ? 'Düzenle' : 'Edit',
      reject: isTr ? 'Reddet' : 'Reject',
    },
    states: {
      loading: isTr ? 'Şikayetler yükleniyor' : 'Loading complaints',
      empty: isTr ? 'Bu filtrelerde şikayet bulunamadı.' : 'No complaints found for these filters.',
      page: isTr ? 'Sayfa' : 'Page',
      previous: isTr ? 'Önceki' : 'Previous',
      next: isTr ? 'Sonraki' : 'Next',
    },
    model: {
      title: isTr ? 'Çalışma modeli' : 'Operating model',
      description: isTr
        ? 'Şikayetvar tarafında taslaklar otomatik üretilir. Platforma gönderim ise her zaman manuel onayla yapılır.'
        : 'Drafts are generated automatically for Sikayetvar. Posting to the platform is always done with manual approval.',
      settingsTitle: isTr ? 'Şikayetvar ayarları' : 'Sikayetvar settings',
      settingsSubtitle: isTr ? 'Empatik ton ve imza ayarları' : 'Empathetic tone and signature settings',
      autoGenerateTitle: isTr ? 'Taslak üretimi açık' : 'Draft generation enabled',
      autoGenerateDesc: isTr ? 'Yeni şikayetler için AI taslak oluştur' : 'Generate AI drafts for new complaints',
      language: isTr ? 'Dil' : 'Language',
      languagePlaceholder: isTr ? 'Dil seçin' : 'Select language',
      languageTurkish: isTr ? 'Türkçe' : 'Turkish',
      languageGerman: isTr ? 'Almanca' : 'German',
      tone: isTr ? 'Ton talimatı' : 'Tone instruction',
      tonePlaceholder: isTr ? 'Örn. Daha empatik ama çözüm odaklı yaz.' : 'Example: Write more empathetically but keep it solution-oriented.',
      signature: isTr ? 'İmza' : 'Signature',
      signaturePlaceholder: isTr ? 'Örn. Saygılarımızla, Telyx Destek Ekibi' : 'Example: Kind regards, Telyx Support Team',
      save: isTr ? 'Ayarları kaydet' : 'Save settings',
    },
    dialog: {
      title: isTr ? 'Şikayet cevabını düzenle' : 'Edit complaint reply',
      description: isTr ? 'Düzenlenen cevap kaydedildikten sonra platforma gönderilir.' : 'The edited reply is sent to the platform after it is saved.',
      replyLabel: isTr ? 'Cevap metni' : 'Reply text',
      characterCount: isTr ? 'karakter' : 'characters',
      cancel: isTr ? 'Vazgeç' : 'Cancel',
      saveAndSend: isTr ? 'Kaydet ve Gönder' : 'Save and Send',
    },
    toasts: {
      approveSuccess: isTr ? 'Cevap platforma gönderildi' : 'Reply sent to the platform',
      approveError: isTr ? 'Cevap gönderilemedi' : 'Failed to send the reply',
      editSuccess: isTr ? 'Düzenlenen cevap gönderildi' : 'Edited reply sent',
      editError: isTr ? 'Düzenlenen cevap gönderilemedi' : 'Failed to send the edited reply',
      rejectPromptTitle: isTr ? 'Reddetme nedeni' : 'Reason for rejection',
      rejectPromptDefault: isTr ? 'Bu şikayete şu aşamada platform üzerinden yanıt verilmeyecek.' : 'This complaint will not be answered on the platform at this stage.',
      rejectSuccess: isTr ? 'Şikayet reddedildi' : 'Complaint rejected',
      rejectError: isTr ? 'Şikayet reddedilemedi' : 'Failed to reject the complaint',
      settingsSuccess: isTr ? 'Şikayet ayarları güncellendi' : 'Complaint settings updated',
      settingsError: isTr ? 'Şikayet ayarları güncellenemedi' : 'Failed to update complaint settings',
    },
    statuses: {
      PENDING: isTr ? 'Onay bekliyor' : 'Pending approval',
      APPROVED: isTr ? 'Onaylandı' : 'Approved',
      POSTED: isTr ? 'Gönderildi' : 'Posted',
      REJECTED: isTr ? 'Reddedildi' : 'Rejected',
      CLOSED: isTr ? 'Kapandı' : 'Closed',
      ERROR: isTr ? 'Hata' : 'Error',
    },
  };
}

function getStatusMeta(copy) {
  return {
    PENDING: { label: copy.statuses.PENDING, className: 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300' },
    APPROVED: { label: copy.statuses.APPROVED, className: 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300' },
    POSTED: { label: copy.statuses.POSTED, className: 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300' },
    REJECTED: { label: copy.statuses.REJECTED, className: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300' },
    CLOSED: { label: copy.statuses.CLOSED, className: 'bg-neutral-200 text-neutral-700 dark:bg-neutral-800 dark:text-neutral-300' },
    ERROR: { label: copy.statuses.ERROR, className: 'bg-rose-100 text-rose-700 dark:bg-rose-900/30 dark:text-rose-300' },
  };
}

function formatDate(value, locale) {
  if (!value) return '-';
  return new Date(value).toLocaleString(locale === 'tr' ? 'tr-TR' : 'en-US', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function ComplaintStatCard({ title, value, hint }) {
  return (
    <div className="rounded-xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-950">
      <div className="text-sm text-neutral-500 dark:text-neutral-400">{title}</div>
      <div className="mt-2 text-3xl font-semibold text-neutral-900 dark:text-white">{value}</div>
      <div className="mt-2 text-xs text-neutral-500 dark:text-neutral-400">{hint}</div>
    </div>
  );
}

function ComplaintCard({ item, onApprove, onEdit, onReject, loading, copy, locale }) {
  const STATUS_META = getStatusMeta(copy);
  const statusMeta = STATUS_META[item.status] || STATUS_META.PENDING;

  return (
    <div className="rounded-xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-950">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
        <div className="space-y-3">
          <div className="flex flex-wrap items-center gap-2">
            <Badge className={statusMeta.className}>{statusMeta.label}</Badge>
            <Badge variant="outline">{copy.card.platform}</Badge>
            {item.sourceCreatedAt && (
              <span className="text-xs text-neutral-500 dark:text-neutral-400">
                {copy.card.openedAt}: {formatDate(item.sourceCreatedAt, locale)}
              </span>
            )}
          </div>

          <div>
            <div className="font-semibold text-neutral-900 dark:text-white">{item.title || copy.card.noTitle}</div>
            <div className="text-xs text-neutral-500 dark:text-neutral-400">
              {item.customerName || copy.card.customerFallback} • {item.customerCity || copy.card.cityFallback}
            </div>
          </div>

          <div>
            <div className="text-xs font-medium uppercase tracking-wide text-neutral-500 dark:text-neutral-400">{copy.card.complaint}</div>
            <p className="mt-1 whitespace-pre-wrap text-sm text-neutral-800 dark:text-neutral-100">{item.complaintText}</p>
          </div>

          <div>
            <div className="flex items-center gap-2 text-xs font-medium uppercase tracking-wide text-neutral-500 dark:text-neutral-400">
              <Sparkles className="h-3.5 w-3.5" />
              {copy.card.aiDraft}
            </div>
            <p className="mt-1 whitespace-pre-wrap text-sm text-neutral-800 dark:text-neutral-100">
              {item.finalReply || item.generatedReply || copy.card.noDraft}
            </p>
          </div>

          {item.complaintUrl && (
            <a
              href={item.complaintUrl}
              target="_blank"
              rel="noreferrer"
              className="inline-flex text-sm text-teal-700 underline dark:text-teal-300"
            >
              {copy.card.openOnPlatform}
            </a>
          )}

          {item.errorMessage && (
            <div className="rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-sm text-rose-700 dark:border-rose-900/40 dark:bg-rose-950/30 dark:text-rose-300">
              {item.errorMessage}
            </div>
          )}
        </div>

        <div className="flex gap-2 lg:min-w-[240px] lg:flex-col">
          <Button
            onClick={() => onApprove(item)}
            disabled={loading || !item.generatedReply || item.status === 'POSTED' || item.status === 'CLOSED'}
          >
            <CheckCircle2 className="mr-2 h-4 w-4" />
            {copy.card.approveAndSend}
          </Button>
          <Button
            variant="outline"
            onClick={() => onEdit(item)}
            disabled={loading || item.status === 'POSTED' || item.status === 'CLOSED'}
          >
            {copy.card.edit}
          </Button>
          <Button
            variant="outline"
            onClick={() => onReject(item)}
            disabled={loading || item.status === 'POSTED'}
          >
            <XCircle className="mr-2 h-4 w-4" />
            {copy.card.reject}
          </Button>
        </div>
      </div>
    </div>
  );
}

export default function ComplaintsPage() {
  const { locale } = useLanguage();
  const copy = getComplaintsCopy(locale);
  const pageHelp = getPageHelp('integrations', locale);
  const { data: sikayetvarStatus } = useSikayetvarStatus();
  const hasConnectedIntegration = Boolean(sikayetvarStatus?.connected);

  const [filters, setFilters] = useState({
    page: 1,
    limit: 20,
    platform: 'ALL',
    status: 'ALL',
    search: '',
    fromDate: '',
    toDate: '',
  });
  const [editDialogOpen, setEditDialogOpen] = useState(false);
  const [selectedThread, setSelectedThread] = useState(null);
  const [editedReply, setEditedReply] = useState('');
  const [settingsState, setSettingsState] = useState({});

  const threadsQuery = useComplaintThreads(filters);
  const statsQuery = useComplaintStats();
  const settingsQuery = useComplaintSettings();
  const approveThread = useApproveComplaintThread();
  const editThread = useEditComplaintThread();
  const rejectThread = useRejectComplaintThread();
  const updateSettings = useUpdateComplaintSettings();

  useEffect(() => {
    if (!settingsQuery.data?.settings) {
      return;
    }

    const nextState = {};
    for (const item of settingsQuery.data.settings) {
      nextState[item.platform] = {
        language: item.complaintSettings?.language || 'tr',
        toneInstructions: item.complaintSettings?.toneInstructions || '',
        signature: item.complaintSettings?.signature || '',
        autoGenerate: item.complaintSettings?.autoGenerate !== false,
      };
    }
    setSettingsState(nextState);
  }, [settingsQuery.data]);

  const items = threadsQuery.data?.items || [];
  const pagination = threadsQuery.data?.pagination || { page: 1, totalPages: 1 };
  const stats = statsQuery.data || {};

  const handleApprove = async (item) => {
    try {
      await approveThread.mutateAsync({
        id: item.id,
        answerText: item.finalReply || item.generatedReply,
      });
      toast.success(copy.toasts.approveSuccess);
    } catch (error) {
      toast.error(error.response?.data?.error || copy.toasts.approveError);
    }
  };

  const handleEditOpen = (item) => {
    setSelectedThread(item);
    setEditedReply(item.finalReply || item.generatedReply || '');
    setEditDialogOpen(true);
  };

  const handleEditSave = async () => {
    if (!selectedThread) return;

    try {
      await editThread.mutateAsync({
        id: selectedThread.id,
        answerText: editedReply,
      });
      toast.success(copy.toasts.editSuccess);
      setEditDialogOpen(false);
      setSelectedThread(null);
      setEditedReply('');
    } catch (error) {
      toast.error(error.response?.data?.error || copy.toasts.editError);
    }
  };

  const handleReject = async (item) => {
    const rejectionReason = window.prompt(copy.toasts.rejectPromptTitle, copy.toasts.rejectPromptDefault);
    if (rejectionReason == null) return;

    try {
      await rejectThread.mutateAsync({ id: item.id, rejectionReason });
      toast.success(copy.toasts.rejectSuccess);
    } catch (error) {
      toast.error(error.response?.data?.error || copy.toasts.rejectError);
    }
  };

  const handleSettingsChange = (platform, field, value) => {
    setSettingsState((prev) => ({
      ...prev,
      [platform]: {
        ...(prev[platform] || {}),
        [field]: value,
      },
    }));
  };

  const handleSettingsSave = async (platform) => {
    try {
      await updateSettings.mutateAsync({
        platform,
        complaintSettings: settingsState[platform],
      });
      toast.success(copy.toasts.settingsSuccess);
    } catch (error) {
      toast.error(error.response?.data?.error || copy.toasts.settingsError);
    }
  };

  return (
    <div className="space-y-8">
      <PageIntro
        title={copy.title}
        subtitle={pageHelp?.subtitle || copy.subtitle}
        locale={locale}
        help={pageHelp ? {
          tooltipTitle: pageHelp.tooltipTitle,
          tooltipBody: pageHelp.tooltipBody,
          quickSteps: pageHelp.quickSteps,
        } : undefined}
      />

      {!hasConnectedIntegration && (
        <EmptyState
          icon={AlertTriangle}
          title={copy.emptyTitle}
          description={copy.emptyDescription}
        />
      )}

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <ComplaintStatCard title={copy.stats.total.title} value={stats.total || 0} hint={copy.stats.total.hint} />
        <ComplaintStatCard title={copy.stats.todayTotal.title} value={stats.todayTotal || 0} hint={copy.stats.todayTotal.hint} />
        <ComplaintStatCard title={copy.stats.pending.title} value={stats.pending || 0} hint={copy.stats.pending.hint} />
        <ComplaintStatCard title={copy.stats.posted.title} value={stats.posted || 0} hint={copy.stats.posted.hint} />
      </div>

      <div className="grid gap-6 xl:grid-cols-[2fr,1fr]">
        <div className="space-y-4">
          <div className="rounded-xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-950">
            <div className="flex flex-col gap-4 md:flex-row md:items-end">
              <div className="flex-1">
                <Label>{copy.filters.search}</Label>
                <Input
                  placeholder={copy.filters.searchPlaceholder}
                  value={filters.search}
                  onChange={(event) => setFilters((prev) => ({ ...prev, search: event.target.value, page: 1 }))}
                />
              </div>

              <div className="w-full md:w-[180px]">
                <Label>{copy.filters.status}</Label>
                <Select
                  value={filters.status}
                  onValueChange={(value) => setFilters((prev) => ({ ...prev, status: value, page: 1 }))}
                >
                  <SelectTrigger>
                    <SelectValue placeholder={copy.filters.statusPlaceholder} />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="ALL">{copy.filters.all}</SelectItem>
                    <SelectItem value="PENDING">{copy.filters.pending}</SelectItem>
                    <SelectItem value="POSTED">{copy.filters.posted}</SelectItem>
                    <SelectItem value="REJECTED">{copy.filters.rejected}</SelectItem>
                    <SelectItem value="ERROR">{copy.filters.error}</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="w-full md:w-[180px]">
                <Label>{copy.filters.fromDate}</Label>
                <Input
                  type="date"
                  value={filters.fromDate}
                  onChange={(event) => setFilters((prev) => ({ ...prev, fromDate: event.target.value, page: 1 }))}
                />
              </div>

              <div className="w-full md:w-[180px]">
                <Label>{copy.filters.toDate}</Label>
                <Input
                  type="date"
                  value={filters.toDate}
                  onChange={(event) => setFilters((prev) => ({ ...prev, toDate: event.target.value, page: 1 }))}
                />
              </div>
            </div>
          </div>

          {threadsQuery.isLoading ? (
            <div className="rounded-xl border border-dashed border-neutral-300 bg-white p-10 text-center text-neutral-500 dark:border-neutral-700 dark:bg-neutral-950 dark:text-neutral-400">
              <RefreshCw className="mx-auto mb-3 h-5 w-5 animate-spin" />
              {copy.states.loading}
            </div>
          ) : items.length === 0 ? (
            <div className="rounded-xl border border-dashed border-neutral-300 bg-white p-10 text-center text-neutral-500 dark:border-neutral-700 dark:bg-neutral-950 dark:text-neutral-400">
              {copy.states.empty}
            </div>
          ) : (
            <div className="space-y-4">
              {items.map((item) => (
                <ComplaintCard
                  key={item.id}
                  item={item}
                  onApprove={handleApprove}
                  onEdit={handleEditOpen}
                  onReject={handleReject}
                  loading={approveThread.isPending || editThread.isPending || rejectThread.isPending}
                  copy={copy}
                  locale={locale}
                />
              ))}
            </div>
          )}

          <div className="flex items-center justify-between rounded-xl border border-neutral-200 bg-white px-4 py-3 dark:border-neutral-800 dark:bg-neutral-950">
            <div className="text-sm text-neutral-500 dark:text-neutral-400">
              {copy.states.page} {pagination.page} / {pagination.totalPages}
            </div>
            <div className="flex gap-2">
              <Button
                variant="outline"
                onClick={() => setFilters((prev) => ({ ...prev, page: Math.max(1, prev.page - 1) }))}
                disabled={pagination.page <= 1}
              >
                {copy.states.previous}
              </Button>
              <Button
                variant="outline"
                onClick={() => setFilters((prev) => ({ ...prev, page: Math.min(pagination.totalPages, prev.page + 1) }))}
                disabled={pagination.page >= pagination.totalPages}
              >
                {copy.states.next}
              </Button>
            </div>
          </div>
        </div>

        <div className="space-y-4">
          <div className="rounded-xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-950">
            <div className="flex items-center gap-2 text-sm font-semibold text-neutral-900 dark:text-white">
              <AlertCircle className="h-4 w-4" />
              {copy.model.title}
            </div>
            <p className="mt-2 text-sm text-neutral-600 dark:text-neutral-300">
              {copy.model.description}
            </p>
          </div>

          {(settingsQuery.data?.settings || []).map((item) => {
            const settings = settingsState[item.platform] || {};

            return (
              <div key={item.platform} className="rounded-xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-950">
                <div className="mb-4">
                  <div className="text-sm font-semibold text-neutral-900 dark:text-white">{copy.model.settingsTitle}</div>
                  <div className="text-xs text-neutral-500 dark:text-neutral-400">{copy.model.settingsSubtitle}</div>
                </div>

                <div className="space-y-4">
                  <div className="flex items-center justify-between rounded-lg border border-neutral-200 px-3 py-3 dark:border-neutral-800">
                    <div>
                      <div className="text-sm font-medium text-neutral-900 dark:text-white">{copy.model.autoGenerateTitle}</div>
                      <div className="text-xs text-neutral-500 dark:text-neutral-400">{copy.model.autoGenerateDesc}</div>
                    </div>
                    <Switch
                      checked={settings.autoGenerate !== false}
                      onCheckedChange={(checked) => handleSettingsChange(item.platform, 'autoGenerate', checked)}
                    />
                  </div>

                  <div>
                    <Label>{copy.model.language}</Label>
                    <Select
                      value={settings.language || 'tr'}
                      onValueChange={(value) => handleSettingsChange(item.platform, 'language', value)}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder={copy.model.languagePlaceholder} />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="tr">{copy.model.languageTurkish}</SelectItem>
                        <SelectItem value="en">English</SelectItem>
                        <SelectItem value="de">{copy.model.languageGerman}</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div>
                    <Label>{copy.model.tone}</Label>
                    <Textarea
                      rows={4}
                      placeholder={copy.model.tonePlaceholder}
                      value={settings.toneInstructions || ''}
                      onChange={(event) => handleSettingsChange(item.platform, 'toneInstructions', event.target.value)}
                    />
                  </div>

                  <div>
                    <Label>{copy.model.signature}</Label>
                    <Textarea
                      rows={3}
                      placeholder={copy.model.signaturePlaceholder}
                      value={settings.signature || ''}
                      onChange={(event) => handleSettingsChange(item.platform, 'signature', event.target.value)}
                    />
                  </div>

                  <Button
                    className="w-full"
                    onClick={() => handleSettingsSave(item.platform)}
                    disabled={updateSettings.isPending}
                  >
                    {copy.model.save}
                  </Button>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      <Dialog open={editDialogOpen} onOpenChange={setEditDialogOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>{copy.dialog.title}</DialogTitle>
            <DialogDescription>
              {copy.dialog.description}
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-2">
            <Label>{copy.dialog.replyLabel}</Label>
            <Textarea
              rows={12}
              value={editedReply}
              onChange={(event) => setEditedReply(event.target.value)}
            />
            <div className="text-right text-xs text-neutral-500 dark:text-neutral-400">
              {editedReply.length} {copy.dialog.characterCount}
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setEditDialogOpen(false)}>
              {copy.dialog.cancel}
            </Button>
            <Button onClick={handleEditSave} disabled={editThread.isPending}>
              {copy.dialog.saveAndSend}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
