export const PHONE_NUMBERS_PAGE_COPY = {
  tr: {
    usageSectionTitle: 'Plan ve kullanım özeti',
    usageSectionSubtitle: 'Telefon erişimi, ses dakikaları ve yazılı destek havuzunu aynı ekranda takip edin.',
    supportTitle: 'Destek etkileşimleri',
    supportSubtitle: 'Webchat, WhatsApp destek yanıtları ve e-posta aynı havuzdan düşer.',
    voiceTitle: 'Ses dakikaları',
    voiceSubtitle: 'Telefon kullanımı ayrı ses dakikası olarak izlenir.',
    addOnTitle: 'Ek kullanım bakiyesi',
    addOnSubtitle: 'Add-on bakiyeleri yalnızca mevcut dönem içinde tüketilir.',
    accessTitle: 'Telefon erişimi',
    accessSubtitle: 'Plan, eşzamanlı çağrı ve sıfırlama bilgileri.',
    currentPlan: 'Mevcut plan',
    resetDate: 'Sıfırlama tarihi',
    concurrentCalls: 'Eşzamanlı çağrı',
    walletBalance: 'Cüzdan bakiyesi',
    writtenUnitPrice: 'Yazılı kullanım birim fiyatı',
    voiceUnitPrice: 'Ses dakika birim fiyatı',
    total: 'Toplam',
    used: 'Kullanılan',
    remaining: 'Kalan',
    overage: 'Aşım',
    addOnRemaining: 'Add-on kalan',
    notIncluded: 'Bu pakette dahil değil',
    paygWrittenHint: 'PAYG hesaplarda yazılı kullanım cüzdandan düşer.',
    paygVoiceHint: 'PAYG hesaplarda ses dakikaları cüzdandan düşer.',
    noAddOns: 'Aktif add-on bakiyesi yok.',
    writtenAddOn: 'Yazılı etkileşim add-on',
    voiceAddOn: 'Ses dakikası add-on',
    billingCta: 'Paket ve kullanım',
    numberSectionTitle: 'Telefon numaraları',
    numberSectionSubtitle: 'Numaralarınızın durumunu, atanan asistanı ve temel metadatasını buradan yönetin.',
    provider: 'Sağlayıcı',
    createdAt: 'Eklenme',
    nextBilling: 'Sonraki yenileme',
    phoneLockedTitle: 'Telefon erişimi bu planda kapalı',
    phoneLockedDescription: 'Mevcut numaraları görebilirsiniz ancak yeni numara ekleyemezsiniz. Telefon erişimini açmak için paket veya entitlement güncelleyin.',
    phoneLockedReasonLabel: 'Kilit nedeni',
    usagePoolLabel: 'Ortak yazılı havuz',
    voiceAccessEnabled: 'Telefon aktif',
    voiceAccessDisabled: 'Telefon kapalı',
    unknown: 'Bilinmiyor'
  },
  en: {
    usageSectionTitle: 'Plan and usage summary',
    usageSectionSubtitle: 'Track phone access, voice minutes, and the shared written support pool in one place.',
    supportTitle: 'Support interactions',
    supportSubtitle: 'Webchat, WhatsApp support replies, and email draw from the same pool.',
    voiceTitle: 'Voice minutes',
    voiceSubtitle: 'Phone usage is tracked separately as voice minutes.',
    addOnTitle: 'Extra usage balance',
    addOnSubtitle: 'Add-on balances are consumed within the current billing cycle.',
    accessTitle: 'Phone access',
    accessSubtitle: 'Plan, concurrent call, and reset information.',
    currentPlan: 'Current plan',
    resetDate: 'Reset date',
    concurrentCalls: 'Concurrent calls',
    walletBalance: 'Wallet balance',
    writtenUnitPrice: 'Written unit price',
    voiceUnitPrice: 'Voice minute unit price',
    total: 'Total',
    used: 'Used',
    remaining: 'Remaining',
    overage: 'Overage',
    addOnRemaining: 'Add-on remaining',
    notIncluded: 'Not included on this plan',
    paygWrittenHint: 'Written usage is deducted from the wallet on PAYG accounts.',
    paygVoiceHint: 'Voice minutes are deducted from the wallet on PAYG accounts.',
    noAddOns: 'No active add-on balance.',
    writtenAddOn: 'Written interaction add-on',
    voiceAddOn: 'Voice minute add-on',
    billingCta: 'Plan & usage',
    numberSectionTitle: 'Phone numbers',
    numberSectionSubtitle: 'Manage your number status, assigned assistant, and core metadata here.',
    provider: 'Provider',
    createdAt: 'Created',
    nextBilling: 'Next renewal',
    phoneLockedTitle: 'Phone access is disabled on this plan',
    phoneLockedDescription: 'You can still review existing numbers, but new numbers are disabled until plan or entitlement access is updated.',
    phoneLockedReasonLabel: 'Lock reason',
    usagePoolLabel: 'Shared written pool',
    voiceAccessEnabled: 'Phone enabled',
    voiceAccessDisabled: 'Phone disabled',
    unknown: 'Unknown'
  }
};

export function getPhoneNumbersCopy(locale = 'tr') {
  return PHONE_NUMBERS_PAGE_COPY[locale === 'en' ? 'en' : 'tr'];
}
